// Banco de perguntas da Trilha do Saber (conhecimentos e curiosidades).
// Em cada pergunta, o[0] é sempre a resposta certa — o jogo embaralha as opções na hora
// de mostrar. O campo x é a curiosidade exibida depois que o grupo responde.
import type { CategorySlug } from '../data';

export type CategoriaDoQuiz = CategorySlug | 'brasil' | 'ciencia';

export interface Pergunta {
  id: string; // estável e único, ex.: 'tec-01', 'mus-07', 'bra-12'
  cat: CategoriaDoQuiz;
  nivel: 1 | 2 | 3; // 1 fácil, 2 médio, 3 difícil
  p: string; // a pergunta
  o: [string, string, string, string]; // o[0] é a correta
  x: string; // curiosidade de 1–2 frases que aparece depois da resposta
}

export const CATEGORIAS_DO_QUIZ: { id: CategoriaDoQuiz; rotulo: string; cor: string }[] = [
  { id: 'tecnologia', rotulo: 'Tecnologia', cor: '#2563eb' },
  { id: 'musica', rotulo: 'Música', cor: '#db2777' },
  { id: 'moda', rotulo: 'Moda', cor: '#a21caf' },
  { id: 'cultura', rotulo: 'Cultura', cor: '#c2410c' },
  { id: 'esporte', rotulo: 'Esporte', cor: '#15803d' },
  { id: 'cinema', rotulo: 'Cinema', cor: '#dc2626' },
  { id: 'livros', rotulo: 'Livros', cor: '#7c3aed' },
  { id: 'gastronomia', rotulo: 'Gastronomia', cor: '#b45309' },
  { id: 'viagem', rotulo: 'Viagem', cor: '#0e7490' },
  { id: 'games', rotulo: 'Games', cor: '#4f46e5' },
  { id: 'bem-estar', rotulo: 'Bem-estar', cor: '#0f766e' },
  { id: 'arte', rotulo: 'Arte', cor: '#be123c' },
  { id: 'brasil', rotulo: 'Brasil', cor: '#4d7c0f' },
  { id: 'ciencia', rotulo: 'Ciência e natureza', cor: '#0369a1' },
];

export const PERGUNTAS: Pergunta[] = [
  // ——— Tecnologia ———
  {
    id: 'tec-01', cat: 'tecnologia', nivel: 1,
    p: 'Qual empresa desenvolve o sistema operacional Android?',
    o: ['Google', 'Apple', 'Microsoft', 'Samsung'],
    x: 'O Google comprou a startup Android Inc. em 2005, e o primeiro celular com o sistema chegou às lojas em 2008.',
  },
  {
    id: 'tec-02', cat: 'tecnologia', nivel: 1,
    p: 'Quem fundou a Microsoft ao lado de Paul Allen?',
    o: ['Bill Gates', 'Steve Jobs', 'Steve Wozniak', 'Larry Page'],
    x: 'A empresa nasceu em 1975, em Albuquerque, nos EUA, e só depois se mudou para a região de Seattle.',
  },
  {
    id: 'tec-03', cat: 'tecnologia', nivel: 1,
    p: 'Qual unidade de informação equivale a 8 bits?',
    o: ['Byte', 'Nibble', 'Pixel', 'Hertz'],
    x: 'Nibble é o nome curioso dado a meio byte, ou seja, 4 bits.',
  },
  {
    id: 'tec-04', cat: 'tecnologia', nivel: 1,
    p: 'Qual peça é considerada o "cérebro" do computador, pois executa as instruções dos programas?',
    o: ['Processador (CPU)', 'Memória RAM', 'Placa de vídeo', 'Fonte de alimentação'],
    x: 'CPU é a sigla em inglês para Unidade Central de Processamento. Já a RAM guarda dados temporários enquanto o computador está ligado.',
  },
  {
    id: 'tec-05', cat: 'tecnologia', nivel: 1,
    p: 'Qual rede social usou um passarinho azul como símbolo até 2023?',
    o: ['Twitter', 'Facebook', 'Instagram', 'Orkut'],
    x: 'O passarinho era apelidado de Larry, em homenagem ao astro do basquete Larry Bird. Em 2023, a rede passou a se chamar X.',
  },
  {
    id: 'tec-06', cat: 'tecnologia', nivel: 1,
    p: 'O que significa o "e" da palavra e-mail?',
    o: ['Eletrônico', 'Enviado', 'Expresso', 'Externo'],
    x: 'Foi Ray Tomlinson quem escolheu o símbolo @ para os endereços, em 1971, ao enviar mensagens entre computadores diferentes.',
  },
  {
    id: 'tec-07', cat: 'tecnologia', nivel: 1,
    p: 'Qual empresa brasileira, de São José dos Campos (SP), é uma das maiores fabricantes de aviões do mundo?',
    o: ['Embraer', 'Helibras', 'Avibras', 'Varig'],
    x: 'Fundada em 1969, a Embraer produz jatos comerciais, executivos e militares, vendidos para dezenas de países.',
  },
  {
    id: 'tec-08', cat: 'tecnologia', nivel: 2,
    p: 'Em que ano Steve Jobs apresentou o primeiro iPhone?',
    o: ['2007', '2005', '2009', '2010'],
    x: 'O anúncio foi em janeiro de 2007, e o aparelho chegou às lojas dos EUA no fim de junho do mesmo ano.',
  },
  {
    id: 'tec-09', cat: 'tecnologia', nivel: 2,
    p: 'Qual rede social, criada por um engenheiro do Google, virou febre no Brasil nos anos 2000?',
    o: ['Orkut', 'MySpace', 'Fotolog', 'Friendster'],
    x: 'O nome vem do criador, o turco Orkut Büyükkökten. A rede foi lançada em 2004 e encerrada em 2014.',
  },
  {
    id: 'tec-10', cat: 'tecnologia', nivel: 2,
    p: 'Qual linguagem de programação foi criada no Brasil, na PUC-Rio?',
    o: ['Lua', 'Python', 'Ruby', 'Go'],
    x: 'Criada em 1993, Lua é muito usada em games: o World of Warcraft, por exemplo, usa a linguagem em seus addons.',
  },
  {
    id: 'tec-11', cat: 'tecnologia', nivel: 2,
    p: 'O que significa a sigla USB?',
    o: ['Universal Serial Bus', 'Universal System Board', 'Unified Serial Bridge', 'Ultra Speed Bus'],
    x: 'A primeira versão do padrão saiu em 1996 para acabar com a confusão de cabos e conectores diferentes nos computadores.',
  },
  {
    id: 'tec-12', cat: 'tecnologia', nivel: 2,
    p: 'Quem é considerada a primeira programadora da história?',
    o: ['Ada Lovelace', 'Grace Hopper', 'Marie Curie', 'Hedy Lamarr'],
    x: 'No século 19, ela escreveu um algoritmo para a Máquina Analítica de Charles Babbage, um computador que nunca chegou a ser construído.',
  },
  {
    id: 'tec-13', cat: 'tecnologia', nivel: 2,
    p: 'Qual paulistano cofundou o Instagram ao lado de Kevin Systrom?',
    o: ['Mike Krieger', 'Eduardo Saverin', 'David Vélez', 'Marcos Galperin'],
    x: 'O app foi lançado em 2010 e comprado pelo Facebook em 2012, por cerca de US$ 1 bilhão.',
  },
  {
    id: 'tec-14', cat: 'tecnologia', nivel: 2,
    p: 'Qual empresa japonesa lançou o Walkman, tocador portátil de fitas cassete, em 1979?',
    o: ['Sony', 'Panasonic', 'Toshiba', 'Nintendo'],
    x: 'O Walkman popularizou o hábito de ouvir música com fones de ouvido andando na rua, algo que parecia estranho na época.',
  },
  {
    id: 'tec-15', cat: 'tecnologia', nivel: 3,
    p: 'Qual era o nome original do buscador criado por Larry Page e Sergey Brin, antes de virar Google?',
    o: ['BackRub', 'Googol', 'PageRank', 'Stanford Search'],
    x: 'O nome Google vem de "googol", o número 1 seguido de 100 zeros, numa brincadeira com a enorme quantidade de informação da web.',
  },
  {
    id: 'tec-16', cat: 'tecnologia', nivel: 3,
    p: 'O nome da linguagem de programação Python foi inspirado em quê?',
    o: ['Num grupo de comédia britânico', 'Numa espécie de cobra', 'Num personagem de videogame', 'Num filme de ficção científica'],
    x: 'O holandês Guido van Rossum era fã do grupo Monty Python e lançou a primeira versão da linguagem em 1991.',
  },
  {
    id: 'tec-17', cat: 'tecnologia', nivel: 3,
    p: 'O Linux foi criado em 1991 por um estudante de qual país?',
    o: ['Finlândia', 'Suécia', 'Noruega', 'Alemanha'],
    x: 'Linus Torvalds tinha 21 anos quando anunciou o projeto. O mascote do Linux é um pinguim chamado Tux.',
  },
  {
    id: 'tec-18', cat: 'tecnologia', nivel: 3,
    p: 'Qual computador eletrônico de uso geral, apresentado nos EUA em 1946, ocupava uma sala inteira?',
    o: ['ENIAC', 'UNIVAC', 'Colossus', 'Altair 8800'],
    x: 'O ENIAC pesava cerca de 27 toneladas e funcionava com mais de 17 mil válvulas eletrônicas.',
  },

  // ——— Música ———
  {
    id: 'mus-01', cat: 'musica', nivel: 1,
    p: 'Quem é conhecido como o "Rei do Pop"?',
    o: ['Michael Jackson', 'Elvis Presley', 'Prince', 'Freddie Mercury'],
    x: 'O famoso passo moonwalk ganhou o mundo em 1983, quando ele o apresentou na TV cantando "Billie Jean".',
  },
  {
    id: 'mus-02', cat: 'musica', nivel: 1,
    p: 'Qual cantor é chamado de "Rei" da música brasileira e gravou "Detalhes" e "Como É Grande o Meu Amor por Você"?',
    o: ['Roberto Carlos', 'Erasmo Carlos', 'Tim Maia', 'Wanderley Cardoso'],
    x: 'Nos anos 1960, ele liderou a Jovem Guarda ao lado de Erasmo Carlos, seu parceiro de composição por décadas.',
  },
  {
    id: 'mus-03', cat: 'musica', nivel: 1,
    p: 'Qual estilo musical nasceu no Rio no fim dos anos 1950, com João Gilberto e Tom Jobim?',
    o: ['Bossa nova', 'Tropicália', 'Samba-enredo', 'Forró'],
    x: '"Chega de Saudade", gravada por João Gilberto em 1958, é considerada o marco inicial da bossa nova.',
  },
  {
    id: 'mus-04', cat: 'musica', nivel: 1,
    p: 'Qual banda de Liverpool era formada por John, Paul, George e Ringo?',
    o: ['The Beatles', 'The Rolling Stones', 'The Who', 'Queen'],
    x: 'A foto dos quatro atravessando a faixa de pedestres, na capa de "Abbey Road" (1969), é uma das mais imitadas do mundo.',
  },
  {
    id: 'mus-05', cat: 'musica', nivel: 1,
    p: 'O frevo, ritmo acelerado dançado com sombrinhas coloridas, é típico de qual estado?',
    o: ['Pernambuco', 'Bahia', 'Ceará', 'Maranhão'],
    x: 'O frevo é Patrimônio Cultural Imaterial da Humanidade pela UNESCO desde 2012.',
  },
  {
    id: 'mus-06', cat: 'musica', nivel: 1,
    p: 'Qual instrumento era a marca registrada de Luiz Gonzaga, o Rei do Baião?',
    o: ['Sanfona', 'Viola caipira', 'Cavaquinho', 'Pandeiro'],
    x: 'Nascido em Exu (PE), ele eternizou "Asa Branca", composta em parceria com Humberto Teixeira em 1947.',
  },
  {
    id: 'mus-07', cat: 'musica', nivel: 1,
    p: 'Qual banda britânica gravou "Bohemian Rhapsody"?',
    o: ['Queen', 'Pink Floyd', 'Led Zeppelin', 'Deep Purple'],
    x: 'O vocalista Freddie Mercury nasceu em Zanzibar, na atual Tanzânia, com o nome Farrokh Bulsara.',
  },
  {
    id: 'mus-08', cat: 'musica', nivel: 2,
    p: 'Qual cantora gaúcha ganhou de Vinicius de Moraes o apelido de "Pimentinha"?',
    o: ['Elis Regina', 'Gal Costa', 'Maria Bethânia', 'Nara Leão'],
    x: 'Seu álbum com Tom Jobim, "Elis & Tom" (1974), gravado nos EUA, é um dos discos mais celebrados da música brasileira.',
  },
  {
    id: 'mus-09', cat: 'musica', nivel: 2,
    p: 'Qual movimento dos anos 1960 reuniu Caetano Veloso, Gilberto Gil, Gal Costa e Os Mutantes?',
    o: ['Tropicália', 'Jovem Guarda', 'Bossa nova', 'Clube da Esquina'],
    x: 'O disco-manifesto "Tropicália ou Panis et Circencis", de 1968, misturava guitarra elétrica, ritmos brasileiros e poesia.',
  },
  {
    id: 'mus-10', cat: 'musica', nivel: 2,
    p: 'O Clube da Esquina, de Milton Nascimento e Lô Borges, nasceu em qual cidade?',
    o: ['Belo Horizonte', 'Rio de Janeiro', 'Três Pontas', 'Ouro Preto'],
    x: 'O nome vem de uma esquina do bairro Santa Tereza, em BH, onde os amigos se reuniam para tocar violão.',
  },
  {
    id: 'mus-11', cat: 'musica', nivel: 2,
    p: 'Quem compôs "Aquarela do Brasil", de 1939?',
    o: ['Ary Barroso', 'Noel Rosa', 'Dorival Caymmi', 'Cartola'],
    x: 'A música correu o mundo depois de aparecer no desenho "Alô, Amigos" (1942), da Disney, que apresentou o Zé Carioca.',
  },
  {
    id: 'mus-12', cat: 'musica', nivel: 2,
    p: 'Qual mestre do choro compôs "Carinhoso"?',
    o: ['Pixinguinha', 'Ernesto Nazareth', 'Jacob do Bandolim', 'Waldir Azevedo'],
    x: 'A melodia é do fim da década de 1910, mas a letra, de João de Barro (Braguinha), só foi escrita em 1937.',
  },
  {
    id: 'mus-13', cat: 'musica', nivel: 2,
    p: 'Em que ano aconteceu a primeira edição do Rock in Rio?',
    o: ['1985', '1979', '1991', '1988'],
    x: 'Criado pelo empresário Roberto Medina, o festival teve shows de Queen, Iron Maiden e Ozzy Osbourne.',
  },
  {
    id: 'mus-14', cat: 'musica', nivel: 2,
    p: 'Qual cantora, nascida em Portugal, ficou conhecida como "a Pequena Notável" e fez sucesso em Hollywood?',
    o: ['Carmen Miranda', 'Aracy de Almeida', 'Dalva de Oliveira', 'Emilinha Borba'],
    x: 'Ela chegou ao Brasil com menos de um ano de idade e transformou o turbante com frutas em marca registrada.',
  },
  {
    id: 'mus-15', cat: 'musica', nivel: 3,
    p: 'Quem cantou os versos em inglês de "Garota de Ipanema" no disco "Getz/Gilberto", de 1964?',
    o: ['Astrud Gilberto', 'Nara Leão', 'Miúcha', 'Elis Regina'],
    x: 'O disco ganhou o Grammy de Álbum do Ano em 1965 e ajudou a espalhar a bossa nova pelo mundo.',
  },
  {
    id: 'mus-16', cat: 'musica', nivel: 3,
    p: 'Qual compositor lançou em 1971 "Construção", famosa por versos terminados em proparoxítonas?',
    o: ['Chico Buarque', 'Caetano Veloso', 'Gilberto Gil', 'Milton Nascimento'],
    x: 'Ao longo da letra, as mesmas palavras do fim dos versos são embaralhadas e trocadas de lugar, criando novos sentidos.',
  },
  {
    id: 'mus-17', cat: 'musica', nivel: 3,
    p: 'Hamilton de Holanda é um virtuose brasileiro de qual instrumento?',
    o: ['Bandolim', 'Cavaquinho', 'Violão', 'Sanfona'],
    x: 'Ele popularizou o bandolim de 10 cordas, que tem um par de cordas a mais que o tradicional, de 8.',
  },
  {
    id: 'mus-18', cat: 'musica', nivel: 3,
    p: 'Quem compôs as "Bachianas Brasileiras"?',
    o: ['Heitor Villa-Lobos', 'Carlos Gomes', 'Camargo Guarnieri', 'Ernesto Nazareth'],
    x: 'São nove obras que unem o estilo do alemão Johann Sebastian Bach a ritmos e melodias brasileiras.',
  },

  // ——— Moda ———
  {
    id: 'mod-01', cat: 'moda', nivel: 1,
    p: 'Qual estilista francesa popularizou o "pretinho básico" nos anos 1920?',
    o: ['Coco Chanel', 'Vivienne Westwood', 'Donatella Versace', 'Miuccia Prada'],
    x: 'Em 1926, a Vogue americana chamou o vestido de "o Ford da Chanel", comparando-o ao popular carro Ford T.',
  },
  {
    id: 'mod-02', cat: 'moda', nivel: 1,
    p: 'Qual tecido é usado tradicionalmente para fazer calças jeans?',
    o: ['Denim', 'Linho', 'Cetim', 'Tweed'],
    x: 'O nome "denim" vem do francês "de Nîmes", cidade do sul da França de onde vinha um tecido parecido.',
  },
  {
    id: 'mod-03', cat: 'moda', nivel: 1,
    p: 'Qual modelo brasileira, nascida em Horizontina (RS), virou uma das mais famosas do mundo?',
    o: ['Gisele Bündchen', 'Adriana Lima', 'Isabeli Fontana', 'Raquel Zimmermann'],
    x: 'Gisele tem uma irmã gêmea, Patrícia, e foi por anos uma das modelos mais bem pagas do planeta.',
  },
  {
    id: 'mod-04', cat: 'moda', nivel: 1,
    p: 'Qual é o nome da principal semana de moda realizada em São Paulo?',
    o: ['São Paulo Fashion Week', 'Fashion Rio', 'Minas Trend', 'Dragão Fashion Brasil'],
    x: 'O evento estreou em 1996 com o nome Morumbi Fashion Brasil e passou a se chamar SPFW alguns anos depois.',
  },
  {
    id: 'mod-05', cat: 'moda', nivel: 1,
    p: 'Qual marca brasileira de chinelos de borracha ficou famosa no mundo inteiro?',
    o: ['Havaianas', 'Crocs', 'Birkenstock', 'Dr. Martens'],
    x: 'Lançadas em 1962, as Havaianas foram inspiradas na zori, uma sandália japonesa de palha de arroz.',
  },
  {
    id: 'mod-06', cat: 'moda', nivel: 1,
    p: 'O quimono é a vestimenta tradicional de qual país?',
    o: ['Japão', 'China', 'Coreia do Sul', 'Vietnã'],
    x: 'Em japonês, "kimono" significa literalmente "coisa para vestir".',
  },
  {
    id: 'mod-07', cat: 'moda', nivel: 1,
    p: 'Qual cidade italiana é considerada a capital da moda do país?',
    o: ['Milão', 'Roma', 'Florença', 'Veneza'],
    x: 'A semana de moda de Milão integra as chamadas "Big Four", ao lado das de Paris, Nova York e Londres.',
  },
  {
    id: 'mod-08', cat: 'moda', nivel: 2,
    p: 'Qual estilista lançou em 1947 o "New Look", com cintura bem marcada e saias amplas?',
    o: ['Christian Dior', 'Yves Saint Laurent', 'Hubert de Givenchy', 'Pierre Cardin'],
    x: 'O apelido "New Look" foi dado por Carmel Snow, editora da revista Harper’s Bazaar, logo após o primeiro desfile.',
  },
  {
    id: 'mod-09', cat: 'moda', nivel: 2,
    p: 'Qual imigrante alemão deu nome a uma das marcas de jeans mais famosas do mundo?',
    o: ['Levi Strauss', 'Calvin Klein', 'Tommy Hilfiger', 'Ralph Lauren'],
    x: 'Em 1873, ele e o alfaiate Jacob Davis patentearam a calça de trabalho reforçada com rebites de metal.',
  },
  {
    id: 'mod-10', cat: 'moda', nivel: 2,
    p: 'Qual estilista britânica é associada à popularização da minissaia nos anos 1960?',
    o: ['Mary Quant', 'Vivienne Westwood', 'Stella McCartney', 'Phoebe Philo'],
    x: 'Segundo a própria Mary Quant, a peça foi batizada em homenagem ao seu carro preferido, o Mini.',
  },
  {
    id: 'mod-11', cat: 'moda', nivel: 2,
    p: 'Qual calça larga, presa nos tornozelos, faz parte da pilcha, o traje tradicional gaúcho?',
    o: ['Bombacha', 'Pantalona', 'Saruel', 'Culote'],
    x: 'Uma lei estadual de 1989 oficializou a pilcha como traje de honra no Rio Grande do Sul, para homens e mulheres.',
  },
  {
    id: 'mod-12', cat: 'moda', nivel: 2,
    p: 'O famoso chapéu-panamá, de palha trançada, é tradicionalmente feito em qual país?',
    o: ['Equador', 'Panamá', 'Colômbia', 'México'],
    x: 'O nome pegou porque o chapéu era exportado pelo Panamá. A tecelagem da palha toquilla equatoriana é patrimônio da UNESCO.',
  },
  {
    id: 'mod-13', cat: 'moda', nivel: 2,
    p: 'Qual estilista paulistano tem a caveira como símbolo marcante de sua marca?',
    o: ['Alexandre Herchcovitch', 'Ronaldo Fraga', 'Reinaldo Lourenço', 'Walter Rodrigues'],
    x: 'Formado pela Faculdade Santa Marcelina, em São Paulo, ele também levou suas coleções para a semana de moda de Nova York.',
  },
  {
    id: 'mod-14', cat: 'moda', nivel: 2,
    p: 'Qual tecido barato de algodão, com estampas florais coloridas, é símbolo das festas juninas?',
    o: ['Chita', 'Cambraia', 'Tafetá', 'Organza'],
    x: 'A chita tem origem na Índia, chegou ao Brasil pelas mãos dos portugueses e virou marca da estética popular brasileira.',
  },
  {
    id: 'mod-15', cat: 'moda', nivel: 3,
    p: 'Qual estilista criou em 1966 o "Le Smoking", o smoking pensado para mulheres?',
    o: ['Yves Saint Laurent', 'Coco Chanel', 'Jean Paul Gaultier', 'Karl Lagerfeld'],
    x: 'Aos 21 anos, Saint Laurent assumiu a maison Dior, onde era assistente, após a morte do fundador, em 1957.',
  },
  {
    id: 'mod-16', cat: 'moda', nivel: 3,
    p: 'Qual renda artesanal, tradição no Ceará, é feita sobre uma almofada com pequenas peças de madeira?',
    o: ['Renda de bilro', 'Renda renascença', 'Renda filé', 'Crochê'],
    x: 'Os bilros são as pecinhas de madeira que as rendeiras trocam rapidamente para trançar os fios presos por alfinetes.',
  },
  {
    id: 'mod-17', cat: 'moda', nivel: 3,
    p: 'Qual cidade do agreste de Pernambuco é conhecida como a "capital do jeans"?',
    o: ['Toritama', 'Garanhuns', 'Petrolina', 'Caruaru'],
    x: 'Toritama faz parte do Polo de Confecções do Agreste, um dos maiores centros de produção de roupas do país.',
  },
  {
    id: 'mod-18', cat: 'moda', nivel: 3,
    p: 'Quem fundou a grife Comme des Garçons, em Tóquio, em 1969?',
    o: ['Rei Kawakubo', 'Yohji Yamamoto', 'Issey Miyake', 'Kenzo Takada'],
    x: 'Apesar de ser japonesa, a marca tem nome em francês, que significa "como os garotos".',
  },

  // ——— Cultura ———
  {
    id: 'cul-01', cat: 'cultura', nivel: 1,
    p: 'Qual personagem do folclore brasileiro tem uma perna só, fuma cachimbo e usa gorro vermelho?',
    o: ['Saci-Pererê', 'Curupira', 'Boitatá', 'Caipora'],
    x: 'Diz a lenda que o saci vive nos redemoinhos de vento e que quem consegue pegar seu gorro vermelho ganha poder sobre ele.',
  },
  {
    id: 'cul-02', cat: 'cultura', nivel: 1,
    p: 'Qual ser do folclore tem os pés virados para trás para confundir os caçadores?',
    o: ['Curupira', 'Saci-Pererê', 'Boto-cor-de-rosa', 'Mula sem cabeça'],
    x: 'Protetor das matas, o Curupira já aparece numa carta do padre José de Anchieta, escrita em 1560.',
  },
  {
    id: 'cul-03', cat: 'cultura', nivel: 1,
    p: 'Qual santo é celebrado em 24 de junho, a data mais festejada das festas juninas?',
    o: ['São João', 'Santo Antônio', 'São Pedro', 'São José'],
    x: 'Campina Grande (PB) e Caruaru (PE) disputam há anos o título de "maior São João do mundo".',
  },
  {
    id: 'cul-04', cat: 'cultura', nivel: 1,
    p: 'Em qual cidade amazonense acontece o festival com a disputa entre os bois Garantido e Caprichoso?',
    o: ['Parintins', 'Manaus', 'Tefé', 'Itacoatiara'],
    x: 'O Garantido é vermelho e o Caprichoso é azul. A disputa acontece no Bumbódromo, no fim de junho.',
  },
  {
    id: 'cul-05', cat: 'cultura', nivel: 1,
    p: 'Em qual cidade acontece o Círio de Nazaré, uma das maiores procissões do mundo?',
    o: ['Belém', 'Manaus', 'São Luís', 'Salvador'],
    x: 'Realizado no segundo domingo de outubro, o Círio foi reconhecido pela UNESCO como Patrimônio Imaterial da Humanidade em 2013.',
  },
  {
    id: 'cul-06', cat: 'cultura', nivel: 1,
    p: 'Qual manifestação afro-brasileira mistura luta, dança e música, jogada numa roda ao som do berimbau?',
    o: ['Capoeira', 'Maculelê', 'Jongo', 'Samba de roda'],
    x: 'A roda de capoeira é Patrimônio Cultural Imaterial da Humanidade pela UNESCO desde 2014.',
  },
  {
    id: 'cul-07', cat: 'cultura', nivel: 1,
    p: 'Em qual país se celebra o Día de Muertos, com altares coloridos e caveiras de açúcar?',
    o: ['México', 'Espanha', 'Peru', 'Colômbia'],
    x: 'Os altares, chamados "ofrendas", são enfeitados com a cempasúchil, uma flor laranja parente do nosso cravo-de-defunto.',
  },
  {
    id: 'cul-08', cat: 'cultura', nivel: 2,
    p: 'Qual boneco gigante é o símbolo mais famoso do Carnaval de Olinda?',
    o: ['Homem da Meia-Noite', 'Galo da Madrugada', 'Pierrô Gigante', 'Rei Momo'],
    x: 'O boneco desfila desde 1932 e sai às ruas sempre à meia-noite, na virada do sábado para o domingo de Carnaval.',
  },
  {
    id: 'cul-09', cat: 'cultura', nivel: 2,
    p: 'Qual festa do Maranhão encena a história de um boi que morre e ressuscita?',
    o: ['Bumba meu boi', 'Cavalhada', 'Congada', 'Reisado'],
    x: 'O Complexo Cultural do Bumba meu boi do Maranhão foi reconhecido pela UNESCO como patrimônio da humanidade em 2019.',
  },
  {
    id: 'cul-10', cat: 'cultura', nivel: 2,
    p: 'Como se chama a tradicional cerimônia do chá do Japão?',
    o: ['Chanoyu', 'Ikebana', 'Kabuki', 'Origami'],
    x: 'Nela se usa o matcha, chá verde em pó batido com um pincel de bambu chamado chasen.',
  },
  {
    id: 'cul-11', cat: 'cultura', nivel: 2,
    p: 'Qual destas palavras do português brasileiro vem do tupi?',
    o: ['Pipoca', 'Cafuné', 'Moleque', 'Chimarrão'],
    x: '"Pipoca" vem do tupi e significa algo como "pele estourada". Já "cafuné" e "moleque" vieram do quimbundo, língua africana.',
  },
  {
    id: 'cul-12', cat: 'cultura', nivel: 2,
    p: 'Em qual cidade catarinense acontece a Oktoberfest mais famosa do Brasil?',
    o: ['Blumenau', 'Pomerode', 'Joinville', 'Brusque'],
    x: 'A festa começou em 1984, inspirada na original de Munique, e celebra a colonização alemã no Vale do Itajaí.',
  },
  {
    id: 'cul-13', cat: 'cultura', nivel: 2,
    p: 'Qual manifestação nordestina reúne poetas que improvisam versos cantados ao som da viola?',
    o: ['Repente', 'Aboio', 'Xaxado', 'Maracatu'],
    x: 'Os repentistas se desafiam em duplas: cada um precisa rimar na hora e responder ao verso do outro.',
  },
  {
    id: 'cul-14', cat: 'cultura', nivel: 2,
    p: 'Qual língua de sinais é reconhecida por lei no Brasil desde 2002?',
    o: ['Libras', 'ASL', 'LGP', 'LSF'],
    x: 'Libras é a Língua Brasileira de Sinais e tem gramática própria: não é o português "traduzido" em gestos.',
  },
  {
    id: 'cul-15', cat: 'cultura', nivel: 3,
    p: 'O Kuarup, ritual que homenageia mortos ilustres, é tradicional entre povos de qual região?',
    o: ['Alto Xingu', 'Vale do Javari', 'Serra da Raposa', 'Chapada do Araripe'],
    x: 'No ritual, troncos da madeira kuarup são enfeitados para representar os homenageados, com cantos, danças e a luta huka-huka.',
  },
  {
    id: 'cul-16', cat: 'cultura', nivel: 3,
    p: 'No maracatu nação de Pernambuco, como se chama a boneca carregada no cortejo pela dama do paço?',
    o: ['Calunga', 'Mamulengo', 'Vitalina', 'Emília'],
    x: 'A calunga tem grande importância simbólica e religiosa no maracatu, que desfila com rei, rainha e batuqueiros.',
  },
  {
    id: 'cul-17', cat: 'cultura', nivel: 3,
    p: 'As Cavalhadas de Pirenópolis (GO) encenam batalhas entre quais grupos?',
    o: ['Cristãos e mouros', 'Portugueses e holandeses', 'Bandeirantes e jesuítas', 'Romanos e gregos'],
    x: 'Os cavaleiros cristãos vestem azul e os mouros vestem vermelho, numa tradição inspirada nas histórias de Carlos Magno.',
  },
  {
    id: 'cul-18', cat: 'cultura', nivel: 3,
    p: 'O nheengatu, língua ainda falada no Amazonas, se desenvolveu a partir de qual língua?',
    o: ['Tupi', 'Aruaque', 'Quéchua', 'Iorubá'],
    x: 'Também chamada de "língua geral amazônica", ela é cooficial no município de São Gabriel da Cachoeira (AM).',
  },

  // ——— Esporte ———
  {
    id: 'esp-01', cat: 'esporte', nivel: 1,
    p: 'Em qual Copa do Mundo o Brasil conquistou o pentacampeonato?',
    o: ['2002', '1994', '1998', '2006'],
    x: 'Na final, em Yokohama, no Japão, o Brasil venceu a Alemanha por 2 a 0, com dois gols de Ronaldo.',
  },
  {
    id: 'esp-02', cat: 'esporte', nivel: 1,
    p: 'Qual jogador brasileiro ficou conhecido como o "Rei do Futebol"?',
    o: ['Pelé', 'Garrincha', 'Zico', 'Romário'],
    x: 'Pelé é o único jogador a ganhar três Copas do Mundo: 1958, 1962 e 1970.',
  },
  {
    id: 'esp-03', cat: 'esporte', nivel: 1,
    p: 'Quantos jogadores cada time tem em campo numa partida oficial de futebol?',
    o: ['11', '10', '9', '12'],
    x: 'Pela regra, se um time ficar com menos de sete jogadores em campo, a partida não pode continuar.',
  },
  {
    id: 'esp-04', cat: 'esporte', nivel: 1,
    p: 'Qual piloto brasileiro foi campeão da Fórmula 1 em 1988, 1990 e 1991?',
    o: ['Ayrton Senna', 'Nelson Piquet', 'Emerson Fittipaldi', 'Rubens Barrichello'],
    x: 'Sua primeira vitória na F1 veio no GP de Portugal de 1985, debaixo de muita chuva, pilotando uma Lotus.',
  },
  {
    id: 'esp-05', cat: 'esporte', nivel: 1,
    p: 'Em qual cidade aconteceram os primeiros Jogos Olímpicos da América do Sul, em 2016?',
    o: ['Rio de Janeiro', 'São Paulo', 'Buenos Aires', 'Santiago'],
    x: 'A Rio 2016 marcou a estreia do rúgbi de sete e a volta do golfe, que estava fora das Olimpíadas desde 1904.',
  },
  {
    id: 'esp-06', cat: 'esporte', nivel: 1,
    p: 'Qual estádio carioca foi inaugurado para a Copa do Mundo de 1950?',
    o: ['Maracanã', 'São Januário', 'Engenhão', 'Pacaembu'],
    x: 'Seu nome oficial é Estádio Jornalista Mário Filho, em homenagem ao jornalista que defendeu a construção.',
  },
  {
    id: 'esp-07', cat: 'esporte', nivel: 1,
    p: 'Qual clube brasileiro é conhecido pelo apelido de "Timão"?',
    o: ['Corinthians', 'Palmeiras', 'Santos', 'São Paulo'],
    x: 'O Corinthians foi fundado em 1910 por operários do bairro do Bom Retiro, em São Paulo.',
  },
  {
    id: 'esp-08', cat: 'esporte', nivel: 2,
    p: 'O saque "Jornada nas Estrelas", lançado altíssimo, ficou famoso em qual esporte?',
    o: ['Vôlei', 'Tênis', 'Tênis de mesa', 'Badminton'],
    x: 'Foi criado por Bernard Rajzman, da "geração de prata", vice-campeã olímpica em Los Angeles 1984.',
  },
  {
    id: 'esp-09', cat: 'esporte', nivel: 2,
    p: 'Qual família brasileira ficou famosa por desenvolver o jiu-jitsu brasileiro?',
    o: ['Gracie', 'Nogueira', 'Barbosa', 'Oliveira'],
    x: 'Carlos Gracie aprendeu a luta com o japonês Mitsuyo Maeda, em Belém do Pará, no início do século 20.',
  },
  {
    id: 'esp-10', cat: 'esporte', nivel: 2,
    p: 'Qual tenista brasileiro foi número 1 do mundo e tricampeão de Roland Garros?',
    o: ['Gustavo Kuerten', 'Fernando Meligeni', 'Thomaz Bellucci', 'Marcelo Melo'],
    x: 'Após vencer em 2001, Guga desenhou um coração no saibro de Paris com a raquete e se deitou dentro dele.',
  },
  {
    id: 'esp-11', cat: 'esporte', nivel: 2,
    p: 'Qual jogadora brasileira foi eleita melhor do mundo pela FIFA cinco vezes seguidas, de 2006 a 2010?',
    o: ['Marta', 'Formiga', 'Cristiane', 'Sissi'],
    x: 'Marta voltou a vencer o prêmio em 2018, somando seis títulos de melhor jogadora do mundo.',
  },
  {
    id: 'esp-12', cat: 'esporte', nivel: 2,
    p: 'Quem foi o primeiro brasileiro campeão mundial de Fórmula 1?',
    o: ['Emerson Fittipaldi', 'Nelson Piquet', 'Ayrton Senna', 'Wilson Fittipaldi'],
    x: 'Em 1972, aos 25 anos, ele se tornou o campeão mais jovem da história da F1 até então.',
  },
  {
    id: 'esp-13', cat: 'esporte', nivel: 2,
    p: 'Qual brasileiro ganhou a primeira medalha de ouro olímpica da história do surfe, em Tóquio?',
    o: ['Italo Ferreira', 'Gabriel Medina', 'Filipe Toledo', 'Adriano de Souza'],
    x: 'Nascido em Baía Formosa (RN), Italo aprendeu a surfar usando a tampa de uma caixa de isopor como prancha.',
  },
  {
    id: 'esp-14', cat: 'esporte', nivel: 2,
    p: 'Qual ginasta brasileira ganhou a medalha de ouro no salto nos Jogos de Tóquio?',
    o: ['Rebeca Andrade', 'Daiane dos Santos', 'Flávia Saraiva', 'Jade Barbosa'],
    x: 'Nos mesmos Jogos, ela também foi prata no individual geral, a primeira medalha olímpica de uma ginasta brasileira.',
  },
  {
    id: 'esp-15', cat: 'esporte', nivel: 3,
    p: 'Qual dupla conquistou em Atlanta 1996 o primeiro ouro olímpico de mulheres brasileiras, no vôlei de praia?',
    o: ['Jacqueline e Sandra Pires', 'Adriana Behar e Shelda', 'Juliana e Larissa', 'Ágatha e Bárbara'],
    x: 'A final foi 100% brasileira: Jacqueline e Sandra venceram Mônica Rodrigues e Adriana Samuel, que ficaram com a prata.',
  },
  {
    id: 'esp-16', cat: 'esporte', nivel: 3,
    p: 'Qual brasileiro ganhou o ouro no salto com vara na Rio 2016, com recorde olímpico?',
    o: ['Thiago Braz', 'Augusto Dutra', 'Arthur Zanetti', 'Isaquias Queiroz'],
    x: 'Ele saltou 6,03 m e superou o francês Renaud Lavillenie, então recordista mundial da prova.',
  },
  {
    id: 'esp-17', cat: 'esporte', nivel: 3,
    p: 'Qual foi o primeiro clube brasileiro campeão mundial interclubes, em 1962?',
    o: ['Santos', 'Flamengo', 'Grêmio', 'São Paulo'],
    x: 'Com Pelé em campo, o Santos venceu o Benfica, de Portugal, em 1962, e repetiu o título em 1963 contra o Milan.',
  },
  {
    id: 'esp-18', cat: 'esporte', nivel: 3,
    p: 'Em qual país as regras do futebol moderno foram oficializadas, em 1863?',
    o: ['Inglaterra', 'Escócia', 'França', 'Itália'],
    x: 'No Brasil, o futebol ganhou força com Charles Miller, paulistano filho de britânicos, que trouxe bolas e regras em 1894.',
  },

  // ——— Cinema ———
  {
    id: 'cin-01', cat: 'cinema', nivel: 1,
    p: 'Qual filme brasileiro de 2002 se passa numa favela carioca e é narrado pelo fotógrafo Buscapé?',
    o: ['Cidade de Deus', 'Tropa de Elite', 'Central do Brasil', 'Carandiru'],
    x: 'Dirigido por Fernando Meirelles, com codireção de Kátia Lund, o filme recebeu quatro indicações ao Oscar.',
  },
  {
    id: 'cin-02', cat: 'cinema', nivel: 1,
    p: 'Qual atriz foi indicada ao Oscar de Melhor Atriz por "Central do Brasil" (1998)?',
    o: ['Fernanda Montenegro', 'Fernanda Torres', 'Sônia Braga', 'Glória Pires'],
    x: 'Foi a primeira vez que uma atriz brasileira concorreu ao Oscar de Melhor Atriz, na cerimônia de 1999.',
  },
  {
    id: 'cin-03', cat: 'cinema', nivel: 1,
    p: 'Quem dirigiu "E.T. – O Extraterrestre" (1982)?',
    o: ['Steven Spielberg', 'George Lucas', 'James Cameron', 'Robert Zemeckis'],
    x: 'A cena da bicicleta voando diante da Lua virou o logotipo da Amblin, produtora fundada por Spielberg.',
  },
  {
    id: 'cin-04', cat: 'cinema', nivel: 1,
    p: 'De qual saga é a frase "Que a Força esteja com você"?',
    o: ['Star Wars', 'Star Trek', 'O Senhor dos Anéis', 'Duna'],
    x: 'O primeiro filme da saga estreou em 1977, escrito e dirigido por George Lucas.',
  },
  {
    id: 'cin-05', cat: 'cinema', nivel: 1,
    p: 'Em qual filme da Pixar os brinquedos de um menino chamado Andy ganham vida?',
    o: ['Toy Story', 'Monstros S.A.', 'Up: Altas Aventuras', 'Carros'],
    x: 'Lançado em 1995, "Toy Story" foi o primeiro longa-metragem totalmente animado por computador.',
  },
  {
    id: 'cin-06', cat: 'cinema', nivel: 1,
    p: 'Qual filme de 1972, dirigido por Francis Ford Coppola, conta a saga da família Corleone?',
    o: ['O Poderoso Chefão', 'Os Bons Companheiros', 'Scarface', 'Os Intocáveis'],
    x: 'Marlon Brando ganhou o Oscar de Melhor Ator por viver Vito Corleone, mas recusou o prêmio.',
  },
  {
    id: 'cin-07', cat: 'cinema', nivel: 1,
    p: 'O filme "O Auto da Compadecida" (2000) é baseado na peça de qual autor?',
    o: ['Ariano Suassuna', 'Nelson Rodrigues', 'Dias Gomes', 'João Cabral de Melo Neto'],
    x: 'Matheus Nachtergaele e Selton Mello viveram João Grilo e Chicó, uma das duplas mais queridas do cinema nacional.',
  },
  {
    id: 'cin-08', cat: 'cinema', nivel: 2,
    p: 'Qual filme de Walter Salles deu ao Brasil o primeiro Oscar de Melhor Filme Internacional, em 2025?',
    o: ['Ainda Estou Aqui', 'Central do Brasil', 'Abril Despedaçado', 'Diários de Motocicleta'],
    x: 'Estrelado por Fernanda Torres, o filme também concorreu nas categorias de Melhor Filme e Melhor Atriz.',
  },
  {
    id: 'cin-09', cat: 'cinema', nivel: 2,
    p: 'Qual ator e cineasta ficou famoso interpretando caipiras, como no filme "Jeca Tatu" (1959)?',
    o: ['Amácio Mazzaropi', 'Renato Aragão', 'Ronald Golias', 'Chico Anysio'],
    x: 'Mazzaropi tinha produtora e estúdio próprios em Taubaté (SP), onde hoje funciona um museu em sua homenagem.',
  },
  {
    id: 'cin-10', cat: 'cinema', nivel: 2,
    p: 'Qual dupla de comediantes brilhou nas chanchadas da Atlântida, nos anos 1940 e 1950?',
    o: ['Oscarito e Grande Otelo', 'Didi e Dedé', 'Mussum e Zacarias', 'Chico Anysio e Jô Soares'],
    x: 'A Atlântida Cinematográfica foi fundada no Rio em 1941 e fez sucesso com musicais de Carnaval e paródias de Hollywood.',
  },
  {
    id: 'cin-11', cat: 'cinema', nivel: 2,
    p: 'Qual é o prêmio máximo do Festival de Cannes?',
    o: ['Palma de Ouro', 'Leão de Ouro', 'Urso de Ouro', 'Concha de Ouro'],
    x: 'Em 1962, "O Pagador de Promessas", de Anselmo Duarte, levou a Palma de Ouro, um marco para o cinema brasileiro.',
  },
  {
    id: 'cin-12', cat: 'cinema', nivel: 2,
    p: 'Qual cineasta baiano, líder do Cinema Novo, dirigiu "Deus e o Diabo na Terra do Sol" (1964)?',
    o: ['Glauber Rocha', 'Nelson Pereira dos Santos', 'Cacá Diegues', 'Joaquim Pedro de Andrade'],
    x: 'A frase "uma câmera na mão e uma ideia na cabeça", associada a Glauber, virou lema do Cinema Novo.',
  },
  {
    id: 'cin-13', cat: 'cinema', nivel: 2,
    p: 'Qual turma ganhou em 2019 o filme com atores "Laços", baseado numa graphic novel?',
    o: ['Turma da Mônica', 'Menino Maluquinho', 'Sítio do Picapau Amarelo', 'Os Trapalhões'],
    x: 'O filme adapta a graphic novel dos irmãos Vitor e Lu Cafaggi, inspirada nos personagens de Mauricio de Sousa.',
  },
  {
    id: 'cin-14', cat: 'cinema', nivel: 2,
    p: 'Qual cidade gaúcha sedia um tradicional festival de cinema cujo troféu se chama Kikito?',
    o: ['Gramado', 'Canela', 'Bento Gonçalves', 'Caxias do Sul'],
    x: 'O festival existe desde 1973, e o Kikito, criado pela artista Elisabeth Rosenfeld, representa o deus do bom humor.',
  },
  {
    id: 'cin-15', cat: 'cinema', nivel: 3,
    p: 'Qual filme de Nelson Pereira dos Santos, de 1963, adapta um romance de Graciliano Ramos?',
    o: ['Vidas Secas', 'Rio 40 Graus', 'O Cangaceiro', 'Barravento'],
    x: 'A história da família de retirantes de Fabiano, Sinhá Vitória e da cachorra Baleia é um marco do Cinema Novo.',
  },
  {
    id: 'cin-16', cat: 'cinema', nivel: 3,
    p: 'Qual filme de Kleber Mendonça Filho e Juliano Dornelles ganhou o Prêmio do Júri em Cannes, em 2019?',
    o: ['Bacurau', 'Aquarius', 'O Som ao Redor', 'A Vida Invisível'],
    x: 'A trama se passa num povoado fictício do sertão que, de repente, desaparece dos mapas.',
  },
  {
    id: 'cin-17', cat: 'cinema', nivel: 3,
    p: 'Quem dirigiu "Limite" (1931), clássico do cinema mudo brasileiro?',
    o: ['Mário Peixoto', 'Humberto Mauro', 'Adhemar Gonzaga', 'Alberto Cavalcanti'],
    x: 'Foi o único longa que Mário Peixoto concluiu, e o filme costuma aparecer nas listas dos maiores do cinema nacional.',
  },
  {
    id: 'cin-18', cat: 'cinema', nivel: 3,
    p: 'Qual filme de 1927 é considerado o primeiro longa-metragem com falas sincronizadas?',
    o: ['O Cantor de Jazz', 'Metrópolis', 'Tempos Modernos', 'Cantando na Chuva'],
    x: 'A chegada do cinema falado mudou Hollywood e virou tema do musical "Cantando na Chuva", de 1952.',
  },

  // ——— Livros ———
  {
    id: 'liv-01', cat: 'livros', nivel: 1,
    p: 'Quem escreveu "Dom Casmurro"?',
    o: ['Machado de Assis', 'José de Alencar', 'Aluísio Azevedo', 'Eça de Queirós'],
    x: 'A grande dúvida do livro, se Capitu traiu ou não Bentinho, nunca é respondida pelo autor.',
  },
  {
    id: 'liv-02', cat: 'livros', nivel: 1,
    p: 'Quem criou o Sítio do Picapau Amarelo, com Emília, Narizinho e Pedrinho?',
    o: ['Monteiro Lobato', 'Ziraldo', 'Ruth Rocha', 'Mauricio de Sousa'],
    x: 'A boneca de pano Emília, feita por Tia Nastácia, começa a falar depois de engolir uma "pílula falante".',
  },
  {
    id: 'liv-03', cat: 'livros', nivel: 1,
    p: 'Quem é o autor de "O Menino Maluquinho", o garoto que usava uma panela na cabeça?',
    o: ['Ziraldo', 'Pedro Bandeira', 'Ruth Rocha', 'Monteiro Lobato'],
    x: 'Lançado em 1980, o livro virou filme, peça de teatro, série de TV e revista em quadrinhos.',
  },
  {
    id: 'liv-04', cat: 'livros', nivel: 1,
    p: 'Qual escritor brasileiro é o autor de "O Alquimista"?',
    o: ['Paulo Coelho', 'Jorge Amado', 'Fernando Sabino', 'Érico Veríssimo'],
    x: 'Publicado em 1988, o livro acompanha o pastor Santiago em busca de um tesouro e é um dos brasileiros mais traduzidos no mundo.',
  },
  {
    id: 'liv-05', cat: 'livros', nivel: 1,
    p: 'Quem escreveu a série "Harry Potter"?',
    o: ['J. K. Rowling', 'Suzanne Collins', 'Stephenie Meyer', 'Rick Riordan'],
    x: 'O primeiro livro, "Harry Potter e a Pedra Filosofal", foi publicado no Reino Unido em 1997.',
  },
  {
    id: 'liv-06', cat: 'livros', nivel: 1,
    p: 'Qual poeta escreveu "No meio do caminho tinha uma pedra"?',
    o: ['Carlos Drummond de Andrade', 'Manuel Bandeira', 'Vinicius de Moraes', 'Cecília Meireles'],
    x: 'Publicado em 1928, o poema causou polêmica por causa das repetições e hoje é um dos mais famosos do Brasil.',
  },
  {
    id: 'liv-07', cat: 'livros', nivel: 1,
    p: 'Quem escreveu "O Pequeno Príncipe"?',
    o: ['Antoine de Saint-Exupéry', 'Júlio Verne', 'Victor Hugo', 'Albert Camus'],
    x: 'O autor era aviador e passou por Florianópolis nos anos 1920, onde os moradores o chamavam de "Zé Perri".',
  },
  {
    id: 'liv-08', cat: 'livros', nivel: 2,
    p: 'Qual romance de José de Alencar tem uma heroína cujo nome é um anagrama de "América"?',
    o: ['Iracema', 'O Guarani', 'Senhora', 'Ubirajara'],
    x: 'Publicado em 1865, o livro narra o amor entre a indígena tabajara e o português Martim, no litoral do Ceará.',
  },
  {
    id: 'liv-09', cat: 'livros', nivel: 2,
    p: 'Qual escritora criou Macabéa, a protagonista de "A Hora da Estrela"?',
    o: ['Clarice Lispector', 'Rachel de Queiroz', 'Lygia Fagundes Telles', 'Cecília Meireles'],
    x: 'Clarice nasceu na Ucrânia, em 1920, e chegou ao Brasil ainda bebê. Passou a infância no Recife.',
  },
  {
    id: 'liv-10', cat: 'livros', nivel: 2,
    p: '"Grande Sertão: Veredas", narrado pelo ex-jagunço Riobaldo, é obra de qual autor?',
    o: ['João Guimarães Rosa', 'Graciliano Ramos', 'Euclides da Cunha', 'Ariano Suassuna'],
    x: 'O romance, de 1956, é famoso pela linguagem inventiva, cheia de palavras criadas pelo próprio autor.',
  },
  {
    id: 'liv-11', cat: 'livros', nivel: 2,
    p: 'Qual escritor baiano escreveu "Capitães da Areia" e "Gabriela, Cravo e Canela"?',
    o: ['Jorge Amado', 'João Ubaldo Ribeiro', 'Castro Alves', 'Dias Gomes'],
    x: 'A casa onde ele viveu com a também escritora Zélia Gattai, no bairro do Rio Vermelho, em Salvador, virou museu.',
  },
  {
    id: 'liv-12', cat: 'livros', nivel: 2,
    p: 'De quem é o poema "Canção do Exílio", que começa com "Minha terra tem palmeiras"?',
    o: ['Gonçalves Dias', 'Castro Alves', 'Casimiro de Abreu', 'Olavo Bilac'],
    x: 'O Hino Nacional cita o poema no trecho "Nossos bosques têm mais vida".',
  },
  {
    id: 'liv-13', cat: 'livros', nivel: 2,
    p: 'Qual autora escreveu "Quarto de Despejo", diário de sua vida na favela do Canindé, em São Paulo?',
    o: ['Carolina Maria de Jesus', 'Conceição Evaristo', 'Cora Coralina', 'Rachel de Queiroz'],
    x: 'Publicado em 1960, o livro virou fenômeno de vendas e foi traduzido para mais de dez idiomas.',
  },
  {
    id: 'liv-14', cat: 'livros', nivel: 2,
    p: 'Quem escreveu "Macunaíma, o herói sem nenhum caráter" (1928)?',
    o: ['Mário de Andrade', 'Oswald de Andrade', 'Carlos Drummond de Andrade', 'Manuel Bandeira'],
    x: 'Para criar o livro, Mário se inspirou em lendas indígenas registradas pelo etnólogo alemão Theodor Koch-Grünberg.',
  },
  {
    id: 'liv-15', cat: 'livros', nivel: 3,
    p: 'Qual romance russo começa com a frase "Todas as famílias felizes se parecem"?',
    o: ['Anna Kariênina', 'Guerra e Paz', 'Crime e Castigo', 'Os Irmãos Karamázov'],
    x: 'O livro é de Liev Tolstói, que também escreveu "Guerra e Paz". Já "Crime e Castigo" é de Dostoiévski.',
  },
  {
    id: 'liv-16', cat: 'livros', nivel: 3,
    p: 'Quem foi o primeiro escritor de língua portuguesa a receber o Nobel de Literatura?',
    o: ['José Saramago', 'Jorge Amado', 'Fernando Pessoa', 'Carlos Drummond de Andrade'],
    x: 'O português Saramago recebeu o prêmio em 1998. Entre suas obras mais conhecidas está "Ensaio sobre a Cegueira".',
  },
  {
    id: 'liv-17', cat: 'livros', nivel: 3,
    p: 'Machado de Assis foi o primeiro presidente de qual instituição, fundada em 1897?',
    o: ['Academia Brasileira de Letras', 'Biblioteca Nacional', 'Instituto Histórico e Geográfico', 'Real Gabinete Português de Leitura'],
    x: 'A ABL tem 40 cadeiras, e seus membros são chamados de "imortais".',
  },
  {
    id: 'liv-18', cat: 'livros', nivel: 3,
    p: 'Fernando Pessoa escreveu usando vários heterônimos. Qual destes é um deles?',
    o: ['Álvaro de Campos', 'Mário de Sá-Carneiro', 'Cesário Verde', 'Florbela Espanca'],
    x: 'Os heterônimos mais famosos são Alberto Caeiro, Ricardo Reis e Álvaro de Campos, cada um com estilo e biografia próprios.',
  },

  // ——— Gastronomia ———
  {
    id: 'gas-01', cat: 'gastronomia', nivel: 1,
    p: 'Qual prato brasileiro leva feijão-preto cozido com carnes de porco, como costela, linguiça e paio?',
    o: ['Feijoada', 'Baião de dois', 'Moqueca', 'Vatapá'],
    x: 'No Rio, é tradição servir feijoada às quartas e aos sábados, com arroz, couve, farofa e laranja.',
  },
  {
    id: 'gas-02', cat: 'gastronomia', nivel: 1,
    p: 'O pão de queijo é um símbolo da culinária de qual estado?',
    o: ['Minas Gerais', 'São Paulo', 'Bahia', 'Paraná'],
    x: 'A receita leva polvilho, extraído da mandioca, e por isso é naturalmente sem glúten.',
  },
  {
    id: 'gas-03', cat: 'gastronomia', nivel: 1,
    p: 'Qual bolinho baiano de feijão-fradinho é frito no azeite de dendê?',
    o: ['Acarajé', 'Abará', 'Bolinho de chuva', 'Coxinha'],
    x: 'O abará usa a mesma massa, mas é cozido no vapor, enrolado em folha de bananeira.',
  },
  {
    id: 'gas-04', cat: 'gastronomia', nivel: 1,
    p: 'Qual bebida quente, típica dos gaúchos, é preparada com erva-mate numa cuia?',
    o: ['Chimarrão', 'Tereré', 'Quentão', 'Chá de boldo'],
    x: 'O tereré é a versão gelada da bebida, muito popular no Mato Grosso do Sul e no Paraguai.',
  },
  {
    id: 'gas-05', cat: 'gastronomia', nivel: 1,
    p: 'Em qual país nasceu a pizza margherita?',
    o: ['Itália', 'Estados Unidos', 'Grécia', 'França'],
    x: 'Diz a tradição que ela foi batizada em 1889, em Nápoles, em homenagem à rainha Margherita, com as cores da bandeira italiana.',
  },
  {
    id: 'gas-06', cat: 'gastronomia', nivel: 1,
    p: 'Qual doce de festa é feito com leite condensado e chocolate, e coberto de granulado?',
    o: ['Brigadeiro', 'Beijinho', 'Cajuzinho', 'Quindim'],
    x: 'Segundo a história mais conhecida, o nome homenageia o brigadeiro Eduardo Gomes, nos anos 1940.',
  },
  {
    id: 'gas-07', cat: 'gastronomia', nivel: 1,
    p: 'Qual fruta amazônica, de polpa roxa, é comida no Pará acompanhada de peixe frito e farinha?',
    o: ['Açaí', 'Cupuaçu', 'Bacuri', 'Jabuticaba'],
    x: 'No Pará, o açaí costuma ser consumido sem açúcar e faz parte das refeições do dia a dia, não só da sobremesa.',
  },
  {
    id: 'gas-08', cat: 'gastronomia', nivel: 2,
    p: 'Qual prato paraense é servido numa cuia com tucupi, goma de tapioca, jambu e camarão seco?',
    o: ['Tacacá', 'Maniçoba', 'Vatapá', 'Caruru'],
    x: 'O jambu tem uma substância que provoca uma leve dormência e um formigamento na boca.',
  },
  {
    id: 'gas-09', cat: 'gastronomia', nivel: 2,
    p: 'Qual prato do Espírito Santo, feito em panela de barro, é preparado sem dendê, ao contrário da versão baiana?',
    o: ['Moqueca capixaba', 'Caldeirada', 'Peixada cearense', 'Bobó de camarão'],
    x: 'As panelas de barro são feitas pelas paneleiras de Goiabeiras, em Vitória, ofício registrado como patrimônio cultural do Brasil.',
  },
  {
    id: 'gas-10', cat: 'gastronomia', nivel: 2,
    p: 'O arroz carreteiro, feito com charque, é típico de qual região do Brasil?',
    o: ['Sul', 'Nordeste', 'Norte', 'Centro-Oeste'],
    x: 'O nome vem dos carreteiros, que transportavam cargas em carretas e cozinhavam o charque com arroz pelo caminho.',
  },
  {
    id: 'gas-11', cat: 'gastronomia', nivel: 2,
    p: 'Qual fruto do Cerrado, de cheiro forte, é o ingrediente principal de um famoso arroz goiano?',
    o: ['Pequi', 'Baru', 'Cagaita', 'Buriti'],
    x: 'Debaixo da polpa há espinhos finos, por isso o pequi deve ser roído com cuidado, nunca mordido.',
  },
  {
    id: 'gas-12', cat: 'gastronomia', nivel: 2,
    p: 'Qual queijo italiano cremoso é usado tradicionalmente no tiramisù?',
    o: ['Mascarpone', 'Ricota', 'Gorgonzola', 'Muçarela'],
    x: '"Tiramisù" quer dizer algo como "me levanta" em italiano, talvez pela energia do café e do açúcar.',
  },
  {
    id: 'gas-13', cat: 'gastronomia', nivel: 2,
    p: 'A cachaça é destilada a partir de quê?',
    o: ['Caldo de cana fermentado', 'Melaço de beterraba', 'Mandioca fermentada', 'Milho fermentado'],
    x: 'Pela legislação brasileira, "cachaça" é o nome exclusivo da aguardente de cana produzida no Brasil.',
  },
  {
    id: 'gas-14', cat: 'gastronomia', nivel: 2,
    p: 'O creme que dá corpo ao bobó de camarão é feito com qual ingrediente?',
    o: ['Mandioca', 'Milho', 'Inhame', 'Batata-doce'],
    x: 'De origem africana, o bobó é um clássico baiano que leva também leite de coco e azeite de dendê.',
  },
  {
    id: 'gas-15', cat: 'gastronomia', nivel: 3,
    p: 'A maniçoba, prato típico do Pará, leva folhas de mandioca cozidas por quanto tempo?',
    o: ['Cerca de uma semana', 'Cerca de uma hora', 'Cerca de um dia', 'Cerca de um mês'],
    x: 'O cozimento longo é necessário para eliminar uma substância tóxica presente na folha crua da mandioca-brava.',
  },
  {
    id: 'gas-16', cat: 'gastronomia', nivel: 3,
    p: 'O croissant teria se inspirado no kipferl, pão em forma de meia-lua de qual país?',
    o: ['Áustria', 'Alemanha', 'Hungria', 'Suíça'],
    x: 'A versão folhada e amanteigada que conhecemos hoje se desenvolveu na França, a partir de padarias vienenses em Paris.',
  },
  {
    id: 'gas-17', cat: 'gastronomia', nivel: 3,
    p: 'Qual especiaria, das mais caras do mundo, é feita com os estigmas de uma flor colhidos à mão?',
    o: ['Açafrão', 'Baunilha', 'Cardamomo', 'Cravo-da-índia'],
    x: 'O açafrão verdadeiro vem da flor Crocus sativus. Já o "açafrão-da-terra" é outro nome da cúrcuma, que é uma raiz.',
  },
  {
    id: 'gas-18', cat: 'gastronomia', nivel: 3,
    p: 'O baião de dois, prato típico do Ceará, mistura arroz com qual tipo de feijão?',
    o: ['Feijão-de-corda', 'Feijão-preto', 'Feijão-carioca', 'Feijão-branco'],
    x: 'A receita costuma levar também queijo coalho, manteiga de garrafa e, muitas vezes, carne de sol.',
  },

  // ——— Viagem ———
  {
    id: 'via-01', cat: 'viagem', nivel: 1,
    p: 'Em qual cidade fica a estátua do Cristo Redentor?',
    o: ['Rio de Janeiro', 'Salvador', 'São Paulo', 'Florianópolis'],
    x: 'Inaugurado em 1931 no alto do Corcovado, o monumento tem 30 metros de altura, sem contar o pedestal.',
  },
  {
    id: 'via-02', cat: 'viagem', nivel: 1,
    p: 'As Cataratas do Iguaçu ficam na fronteira do Brasil com qual país?',
    o: ['Argentina', 'Paraguai', 'Uruguai', 'Bolívia'],
    x: 'A maior parte das quedas fica do lado argentino, mas o lado brasileiro oferece a vista panorâmica mais famosa.',
  },
  {
    id: 'via-03', cat: 'viagem', nivel: 1,
    p: 'Qual parque nacional tem dunas brancas com lagoas de água da chuva entre elas?',
    o: ['Lençóis Maranhenses', 'Jalapão', 'Chapada dos Veadeiros', 'Serra da Capivara'],
    x: 'As lagoas se formam com as chuvas do início do ano e costumam estar mais cheias entre junho e setembro.',
  },
  {
    id: 'via-04', cat: 'viagem', nivel: 1,
    p: 'Em qual país fica Machu Picchu, a cidadela inca nos Andes?',
    o: ['Peru', 'Bolívia', 'Equador', 'Chile'],
    x: 'Construída no século 15, a cidadela foi eleita em 2007 uma das Novas Sete Maravilhas do Mundo.',
  },
  {
    id: 'via-05', cat: 'viagem', nivel: 1,
    p: 'Qual monumento de Paris foi construído para a Exposição Universal de 1889?',
    o: ['Torre Eiffel', 'Arco do Triunfo', 'Basílica de Sacré-Cœur', 'Pirâmide do Louvre'],
    x: 'Ela deveria ser desmontada depois de 20 anos, mas foi mantida por ser útil como antena de rádio.',
  },
  {
    id: 'via-06', cat: 'viagem', nivel: 1,
    p: 'Qual arquipélago pernambucano é famoso pelos golfinhos-rotadores e pela Baía do Sancho?',
    o: ['Fernando de Noronha', 'Abrolhos', 'Atol das Rocas', 'Ilhabela'],
    x: 'Para visitar, cada turista paga uma Taxa de Preservação Ambiental calculada pelos dias de estadia.',
  },
  {
    id: 'via-07', cat: 'viagem', nivel: 1,
    p: 'O Encontro das Águas, entre os rios Negro e Solimões, fica perto de qual capital?',
    o: ['Manaus', 'Belém', 'Porto Velho', 'Macapá'],
    x: 'As águas escura e barrenta correm lado a lado por quilômetros sem se misturar, por diferenças de temperatura, velocidade e densidade.',
  },
  {
    id: 'via-08', cat: 'viagem', nivel: 2,
    p: 'Qual cidade mineira foi a primeira do Brasil declarada Patrimônio Mundial pela UNESCO, em 1980?',
    o: ['Ouro Preto', 'Diamantina', 'Tiradentes', 'Mariana'],
    x: 'Ouro Preto foi a capital de Minas Gerais até 1897, quando o posto passou para Belo Horizonte.',
  },
  {
    id: 'via-09', cat: 'viagem', nivel: 2,
    p: 'Em qual estado fica a Chapada Diamantina, com o Morro do Pai Inácio?',
    o: ['Bahia', 'Minas Gerais', 'Goiás', 'Piauí'],
    x: 'Um dos cartões-postais da região é a Cachoeira da Fumaça, cuja água vira névoa antes de chegar ao chão.',
  },
  {
    id: 'via-10', cat: 'viagem', nivel: 2,
    p: 'Qual cidade do Mato Grosso do Sul é famosa pela flutuação em rios de água cristalina?',
    o: ['Bonito', 'Corumbá', 'Dourados', 'Três Lagoas'],
    x: 'A água é tão transparente porque o calcário do solo ajuda as partículas de sujeira a se depositarem no fundo.',
  },
  {
    id: 'via-11', cat: 'viagem', nivel: 2,
    p: 'Em qual país fica Petra, a antiga cidade esculpida nas rochas?',
    o: ['Jordânia', 'Egito', 'Turquia', 'Marrocos'],
    x: 'Petra foi a capital dos nabateus e aparece no filme "Indiana Jones e a Última Cruzada" (1989).',
  },
  {
    id: 'via-12', cat: 'viagem', nivel: 2,
    p: 'Qual rio divide a cidade de Budapeste em Buda e Peste?',
    o: ['Danúbio', 'Reno', 'Volga', 'Sena'],
    x: 'O Danúbio passa por dez países, mais do que qualquer outro rio do mundo.',
  },
  {
    id: 'via-13', cat: 'viagem', nivel: 2,
    p: 'Em qual cidade fica a Escadaria Selarón, coberta de azulejos coloridos?',
    o: ['Rio de Janeiro', 'Salvador', 'São Luís', 'Lisboa'],
    x: 'O artista chileno Jorge Selarón revestiu os degraus com azulejos vindos de mais de 60 países.',
  },
  {
    id: 'via-14', cat: 'viagem', nivel: 2,
    p: 'As gigantescas estátuas moai ficam em qual ilha do Pacífico?',
    o: ['Ilha de Páscoa', 'Taiti', 'Havaí', 'Fiji'],
    x: 'Chamada de Rapa Nui pelos nativos, a ilha pertence ao Chile e fica a cerca de 3.500 km do continente.',
  },
  {
    id: 'via-15', cat: 'viagem', nivel: 3,
    p: 'Qual ponto de João Pessoa (PB) é o extremo leste das Américas?',
    o: ['Ponta do Seixas', 'Cabo de Santo Agostinho', 'Ponta Negra', 'Cabo Frio'],
    x: 'Por isso João Pessoa é conhecida como a cidade onde o sol nasce primeiro nas Américas.',
  },
  {
    id: 'via-16', cat: 'viagem', nivel: 3,
    p: 'A lendária Rota 66 atravessava os EUA de Chicago até qual cidade da Califórnia?',
    o: ['Los Angeles', 'São Francisco', 'San Diego', 'Sacramento'],
    x: 'Criada em 1926, a estrada saiu do sistema oficial de rodovias em 1985, mas virou ícone das viagens de carro.',
  },
  {
    id: 'via-17', cat: 'viagem', nivel: 3,
    p: 'O Monte Roraima, de topo plano, fica na fronteira do Brasil com a Venezuela e com qual outro país?',
    o: ['Guiana', 'Suriname', 'Colômbia', 'Guiana Francesa'],
    x: 'Montanhas de topo plano como ele são chamadas de tepuis e abrigam plantas que só existem ali.',
  },
  {
    id: 'via-18', cat: 'viagem', nivel: 3,
    p: 'Em qual país fica o templo de Angkor Wat?',
    o: ['Camboja', 'Tailândia', 'Vietnã', 'Laos'],
    x: 'Considerado o maior monumento religioso do mundo, Angkor Wat aparece até na bandeira do Camboja.',
  },

  // ——— Games ———
  {
    id: 'gam-01', cat: 'games', nivel: 1,
    p: 'Qual encanador bigodudo é o mascote mais famoso da Nintendo?',
    o: ['Mario', 'Luigi', 'Wario', 'Toad'],
    x: 'Ele estreou em "Donkey Kong" (1981) com o nome de Jumpman, e ainda era carpinteiro, não encanador.',
  },
  {
    id: 'gam-02', cat: 'games', nivel: 1,
    p: 'Qual é o nome do ouriço azul, mascote da Sega?',
    o: ['Sonic', 'Knuckles', 'Tails', 'Shadow'],
    x: 'Sonic estreou em 1991 e foi criado para ser o rival do Mario, com jogos focados em velocidade.',
  },
  {
    id: 'gam-03', cat: 'games', nivel: 1,
    p: 'Qual jogo de peças que caem e formam linhas foi criado por um programador russo?',
    o: ['Tetris', 'Columns', 'Candy Crush', 'Puyo Puyo'],
    x: 'Alexey Pajitnov criou o Tetris em 1984, num computador da Academia de Ciências da União Soviética, em Moscou.',
  },
  {
    id: 'gam-04', cat: 'games', nivel: 1,
    p: 'Em qual jogo você constrói num mundo de blocos e precisa fugir dos Creepers?',
    o: ['Minecraft', 'Roblox', 'Terraria', 'Fortnite'],
    x: 'O jogo foi criado pelo sueco Markus "Notch" Persson e comprado pela Microsoft em 2014.',
  },
  {
    id: 'gam-05', cat: 'games', nivel: 1,
    p: 'Qual personagem amarelo come pastilhas num labirinto enquanto foge de fantasmas?',
    o: ['Pac-Man', 'Kirby', 'Q*bert', 'Frogger'],
    x: 'Segundo o criador, Toru Iwatani, o formato do Pac-Man foi inspirado numa pizza sem uma fatia.',
  },
  {
    id: 'gam-06', cat: 'games', nivel: 1,
    p: 'Qual console da Nintendo, lançado em 2017, funciona tanto na TV quanto como portátil?',
    o: ['Nintendo Switch', 'Wii U', 'Nintendo 3DS', 'GameCube'],
    x: 'Seus controles destacáveis se chamam Joy-Con e podem ser usados separados, um para cada jogador.',
  },
  {
    id: 'gam-07', cat: 'games', nivel: 1,
    p: 'Qual Pokémon elétrico é o inseparável companheiro de Ash no anime?',
    o: ['Pikachu', 'Charmander', 'Bulbasaur', 'Squirtle'],
    x: 'Pikachu evolui para Raichu com a Pedra do Trovão, mas o do Ash sempre se recusou a evoluir.',
  },
  {
    id: 'gam-08', cat: 'games', nivel: 2,
    p: 'Qual empresa brasileira fabricou e vendeu por aqui os consoles da Sega, como o Master System?',
    o: ['Tectoy', 'Gradiente', 'Dynacom', 'CCE'],
    x: 'O Master System fez tanto sucesso no Brasil que a Tectoy continuou fabricando o console por décadas.',
  },
  {
    id: 'gam-09', cat: 'games', nivel: 2,
    p: 'Na série "The Legend of Zelda", qual é o nome do herói controlado pelo jogador?',
    o: ['Link', 'Zelda', 'Ganon', 'Navi'],
    x: 'Muita gente confunde, mas Zelda é a princesa. O primeiro jogo da série foi lançado em 1986.',
  },
  {
    id: 'gam-10', cat: 'games', nivel: 2,
    p: 'Com que nome a série de futebol "FIFA", da EA, passou a ser lançada a partir de 2023?',
    o: ['EA Sports FC', 'eFootball', 'Pro Evolution Soccer', 'Football Manager'],
    x: 'A série começou em 1993 com "FIFA International Soccer" e usou o nome da entidade por cerca de 30 anos.',
  },
  {
    id: 'gam-11', cat: 'games', nivel: 2,
    p: 'Qual lutador de "Street Fighter II" representa o Brasil?',
    o: ['Blanka', 'Guile', 'Dhalsim', 'E. Honda'],
    x: 'Com pele verde e ataques elétricos, Blanka tem o nome verdadeiro de Jimmy e cresceu na selva amazônica.',
  },
  {
    id: 'gam-12', cat: 'games', nivel: 2,
    p: 'Qual jogo de corrida do estúdio gaúcho Aquiris homenageia clássicos como "Top Gear"?',
    o: ['Horizon Chase', 'Forza Horizon', 'Need for Speed', 'Gran Turismo'],
    x: 'A trilha sonora é de Barry Leitch, o mesmo compositor do "Top Gear" do Super Nintendo.',
  },
  {
    id: 'gam-13', cat: 'games', nivel: 2,
    p: 'Qual jogo de 1972, que simulava uma partida de pingue-pongue, foi o primeiro grande sucesso da Atari?',
    o: ['Pong', 'Breakout', 'Asteroids', 'Space Invaders'],
    x: 'Conta a lenda que a primeira máquina de "Pong", instalada num bar, parou de funcionar de tão cheia de moedas.',
  },
  {
    id: 'gam-14', cat: 'games', nivel: 2,
    p: 'Qual empresa lançou o console PlayStation, em 1994?',
    o: ['Sony', 'Nintendo', 'Sega', 'Microsoft'],
    x: 'O PlayStation nasceu depois que uma parceria entre Sony e Nintendo para um leitor de CD do Super Nintendo foi desfeita.',
  },
  {
    id: 'gam-15', cat: 'games', nivel: 3,
    p: 'Qual personagem brasileira estrelou uma versão do game "Wonder Boy in Monster Land" para o Master System?',
    o: ['Mônica', 'Emília', 'Narizinho', 'Dona Benta'],
    x: 'Em "Mônica no Castelo do Dragão", a Tectoy trocou o herói do jogo original pela personagem de Mauricio de Sousa.',
  },
  {
    id: 'gam-16', cat: 'games', nivel: 3,
    p: 'Qual jogo mineiro, de 2018, tem nome inspirado numa guerreira do Quilombo dos Palmares?',
    o: ['Dandara', 'Celeste', 'Hollow Knight', 'Cuphead'],
    x: 'Criado pelo estúdio Long Hat House, de Belo Horizonte, o jogo faz a heroína saltar entre chão, paredes e teto.',
  },
  {
    id: 'gam-17', cat: 'games', nivel: 3,
    p: 'Qual foi o primeiro console de videogame doméstico, lançado em 1972?',
    o: ['Magnavox Odyssey', 'Atari 2600', 'Intellivision', 'ColecoVision'],
    x: 'Criado por Ralph Baer, o Odyssey usava películas coloridas presas na tela da TV para simular os cenários.',
  },
  {
    id: 'gam-18', cat: 'games', nivel: 3,
    p: 'Qual jogo do Atari popularizou o termo "easter egg" ao esconder o nome do criador numa sala secreta?',
    o: ['Adventure', 'Pitfall!', 'Pac-Man', 'Space Invaders'],
    x: 'Warren Robinett fez isso porque a Atari não dava crédito aos programadores. A empresa decidiu chamar essas surpresas de "ovos de Páscoa".',
  },

  // ——— Bem-estar ———
  {
    id: 'bem-01', cat: 'bem-estar', nivel: 1,
    p: 'Qual prática de origem indiana combina posturas, respiração e meditação?',
    o: ['Yoga', 'Tai chi chuan', 'Pilates', 'Reiki'],
    x: 'A palavra "yoga" vem do sânscrito e costuma ser traduzida como "união".',
  },
  {
    id: 'bem-02', cat: 'bem-estar', nivel: 1,
    p: 'Qual arte marcial chinesa, de movimentos lentos e fluidos, é praticada como exercício ao ar livre?',
    o: ['Tai chi chuan', 'Karatê', 'Muay thai', 'Judô'],
    x: 'Na China, é comum ver grupos praticando tai chi em parques logo nas primeiras horas da manhã.',
  },
  {
    id: 'bem-03', cat: 'bem-estar', nivel: 1,
    p: 'Qual método de exercícios, criado por um alemão no início do século 20, foca no fortalecimento do centro do corpo?',
    o: ['Pilates', 'Crossfit', 'Zumba', 'Yoga'],
    x: 'Joseph Pilates chamava seu método de "Contrologia" e começou a desenvolvê-lo durante a Primeira Guerra Mundial.',
  },
  {
    id: 'bem-04', cat: 'bem-estar', nivel: 1,
    p: 'Qual vitamina o corpo produz quando a pele recebe luz do sol?',
    o: ['Vitamina D', 'Vitamina C', 'Vitamina A', 'Vitamina B12'],
    x: 'A vitamina D ajuda o corpo a absorver o cálcio, essencial para ossos e dentes.',
  },
  {
    id: 'bem-05', cat: 'bem-estar', nivel: 1,
    p: 'Quantas horas de sono por noite costumam ser recomendadas para a maioria dos adultos?',
    o: ['7 a 9 horas', '4 a 5 horas', '5 a 6 horas', '10 a 12 horas'],
    x: 'Crianças e adolescentes precisam de ainda mais horas de sono do que os adultos.',
  },
  {
    id: 'bem-06', cat: 'bem-estar', nivel: 1,
    p: 'Como se chama a prática de prestar atenção plena ao momento presente, sem julgamentos?',
    o: ['Mindfulness', 'Detox', 'Coaching', 'Biohacking'],
    x: 'O programa MBSR, criado por Jon Kabat-Zinn em 1979, ajudou a levar o mindfulness para hospitais e clínicas.',
  },
  {
    id: 'bem-07', cat: 'bem-estar', nivel: 1,
    p: 'Qual é o maior órgão do corpo humano?',
    o: ['Pele', 'Fígado', 'Pulmão', 'Intestino'],
    x: 'Entre os órgãos internos, o maior é o fígado. A pele de um adulto pode chegar perto de 2 m² de área.',
  },
  {
    id: 'bem-08', cat: 'bem-estar', nivel: 2,
    p: 'Qual hormônio ligado ao sono é produzido principalmente quando está escuro?',
    o: ['Melatonina', 'Adrenalina', 'Insulina', 'Cortisol'],
    x: 'Por isso, a luz forte de telas à noite pode atrapalhar o sono: ela "engana" o relógio biológico.',
  },
  {
    id: 'bem-09', cat: 'bem-estar', nivel: 2,
    p: 'O "banho de floresta", prática de passar tempo imerso na natureza, surgiu em qual país?',
    o: ['Japão', 'Suécia', 'Canadá', 'Finlândia'],
    x: 'O termo japonês "shinrin-yoku" foi criado nos anos 1980 pela agência florestal do país.',
  },
  {
    id: 'bem-10', cat: 'bem-estar', nivel: 2,
    p: 'Qual palavra dinamarquesa resume a ideia de aconchego, calma e bons momentos em casa?',
    o: ['Hygge', 'Lagom', 'Fika', 'Sisu'],
    x: 'Velas, cobertores e boas conversas são símbolos do hygge, que ajuda a enfrentar os longos invernos da Dinamarca.',
  },
  {
    id: 'bem-11', cat: 'bem-estar', nivel: 2,
    p: 'Qual palavra japonesa significa algo como "razão de viver"?',
    o: ['Ikigai', 'Kaizen', 'Wabi-sabi', 'Umami'],
    x: '"Kaizen", outra palavra japonesa famosa, é a filosofia da melhoria contínua, feita aos pouquinhos.',
  },
  {
    id: 'bem-12', cat: 'bem-estar', nivel: 2,
    p: 'Quantos litros de sangue, em média, circulam no corpo de um adulto?',
    o: ['Cerca de 5 litros', 'Cerca de 1 litro', 'Cerca de 12 litros', 'Cerca de 20 litros'],
    x: 'Em repouso, o coração bombeia mais ou menos esse mesmo volume a cada minuto.',
  },
  {
    id: 'bem-13', cat: 'bem-estar', nivel: 2,
    p: 'Qual técnica de foco divide o trabalho em blocos de 25 minutos com pausas curtas?',
    o: ['Pomodoro', 'Kanban', 'GTD', 'Matriz de Eisenhower'],
    x: 'O nome vem do timer de cozinha em forma de tomate ("pomodoro", em italiano) usado pelo criador, Francesco Cirillo.',
  },
  {
    id: 'bem-14', cat: 'bem-estar', nivel: 2,
    p: 'Segundo a OMS, adultos devem fazer no mínimo quantos minutos de atividade física moderada por semana?',
    o: ['150 minutos', '30 minutos', '60 minutos', '500 minutos'],
    x: 'A recomendação é de 150 a 300 minutos por semana, o que dá, por exemplo, 30 minutos em cinco dias.',
  },
  {
    id: 'bem-15', cat: 'bem-estar', nivel: 3,
    p: 'Qual região do cérebro tem papel central na formação de novas memórias?',
    o: ['Hipocampo', 'Cerebelo', 'Hipotálamo', 'Bulbo'],
    x: 'O nome vem do grego e significa "cavalo-marinho", por causa do formato dessa estrutura.',
  },
  {
    id: 'bem-16', cat: 'bem-estar', nivel: 3,
    p: 'O relógio biológico, ou ritmo circadiano, segue um ciclo de aproximadamente quanto tempo?',
    o: ['24 horas', '12 horas', '7 dias', '90 minutos'],
    x: 'Em 2017, o Nobel de Medicina premiou três cientistas que desvendaram os genes que controlam esse relógio.',
  },
  {
    id: 'bem-17', cat: 'bem-estar', nivel: 3,
    p: 'Qual monge vietnamita ajudou a popularizar a meditação da atenção plena no Ocidente?',
    o: ['Thich Nhat Hanh', 'Dalai Lama', 'Deepak Chopra', 'Eckhart Tolle'],
    x: 'Ele fundou a comunidade Plum Village, na França, e escreveu dezenas de livros sobre viver o momento presente.',
  },
  {
    id: 'bem-18', cat: 'bem-estar', nivel: 3,
    p: 'Em qual fase do sono os sonhos costumam ser mais vívidos?',
    o: ['Sono REM', 'Sono N1', 'Sono N2', 'Sono N3'],
    x: 'REM é a sigla em inglês para "movimento rápido dos olhos": nessa fase, os olhos se mexem sob as pálpebras fechadas.',
  },

  // ——— Arte ———
  {
    id: 'art-01', cat: 'arte', nivel: 1,
    p: 'Quem pintou a "Mona Lisa"?',
    o: ['Leonardo da Vinci', 'Michelangelo', 'Rafael', 'Botticelli'],
    x: 'O quadro fica no Museu do Louvre, em Paris, protegido por um vidro blindado.',
  },
  {
    id: 'art-02', cat: 'arte', nivel: 1,
    p: 'Qual pintor holandês criou "A Noite Estrelada"?',
    o: ['Vincent van Gogh', 'Rembrandt', 'Piet Mondrian', 'Frans Hals'],
    x: 'Pintado em 1889, no sul da França, o quadro hoje está no MoMA, o Museu de Arte Moderna de Nova York.',
  },
  {
    id: 'art-03', cat: 'arte', nivel: 1,
    p: 'Qual pintora mexicana ficou famosa por seus autorretratos e pelas sobrancelhas marcantes?',
    o: ['Frida Kahlo', 'Tarsila do Amaral', 'Georgia O’Keeffe', 'Remedios Varo'],
    x: 'Sua casa na Cidade do México, a Casa Azul, virou um museu dedicado à artista.',
  },
  {
    id: 'art-04', cat: 'arte', nivel: 1,
    p: 'Quem pintou o "Abaporu", em 1928?',
    o: ['Tarsila do Amaral', 'Anita Malfatti', 'Di Cavalcanti', 'Candido Portinari'],
    x: 'O nome vem do tupi e significa "homem que come gente". A tela inspirou o Movimento Antropofágico.',
  },
  {
    id: 'art-05', cat: 'arte', nivel: 1,
    p: 'Quem pintou o teto da Capela Sistina, no Vaticano?',
    o: ['Michelangelo', 'Leonardo da Vinci', 'Rafael', 'Caravaggio'],
    x: 'Ele trabalhou no teto de 1508 a 1512, mesmo se considerando mais escultor do que pintor.',
  },
  {
    id: 'art-06', cat: 'arte', nivel: 1,
    p: 'Qual escultor francês criou "O Pensador"?',
    o: ['Auguste Rodin', 'Michelangelo', 'Donatello', 'Gian Lorenzo Bernini'],
    x: 'A escultura nasceu como parte de "A Porta do Inferno", obra inspirada na "Divina Comédia", de Dante.',
  },
  {
    id: 'art-07', cat: 'arte', nivel: 1,
    p: 'Qual arquiteto projetou os principais prédios de Brasília, como o Congresso e a Catedral?',
    o: ['Oscar Niemeyer', 'Lúcio Costa', 'Lina Bo Bardi', 'Paulo Mendes da Rocha'],
    x: 'O plano urbanístico da cidade, o Plano Piloto, foi criado pelo urbanista Lúcio Costa.',
  },
  {
    id: 'art-08', cat: 'arte', nivel: 2,
    p: 'Qual pintor brasileiro criou os painéis "Guerra e Paz", na sede da ONU, em Nova York?',
    o: ['Candido Portinari', 'Di Cavalcanti', 'Alfredo Volpi', 'Lasar Segall'],
    x: 'Filho de imigrantes italianos, Portinari nasceu em Brodowski (SP), onde sua casa de infância virou museu.',
  },
  {
    id: 'art-09', cat: 'arte', nivel: 2,
    p: 'Qual artista do Brasil colonial esculpiu os 12 profetas de pedra-sabão de Congonhas (MG)?',
    o: ['Aleijadinho', 'Mestre Ataíde', 'Mestre Valentim', 'Frei Jesuíno do Monte Carmelo'],
    x: 'As estátuas ficam no adro do Santuário do Bom Jesus de Matosinhos, reconhecido como Patrimônio Mundial pela UNESCO.',
  },
  {
    id: 'art-10', cat: 'arte', nivel: 2,
    p: 'Qual arquiteta projetou o MASP, famoso pelo grande vão livre na Avenida Paulista?',
    o: ['Lina Bo Bardi', 'Zaha Hadid', 'Lota de Macedo Soares', 'Carmen Portinho'],
    x: 'O vão livre, de mais de 70 metros, virou uma praça coberta usada para feiras, shows e encontros.',
  },
  {
    id: 'art-11', cat: 'arte', nivel: 2,
    p: 'A qual movimento artístico pertence Salvador Dalí, famoso pelos relógios derretidos?',
    o: ['Surrealismo', 'Cubismo', 'Impressionismo', 'Barroco'],
    x: 'O quadro com os relógios moles se chama "A Persistência da Memória" e foi pintado em 1931.',
  },
  {
    id: 'art-12', cat: 'arte', nivel: 2,
    p: 'Qual pintor impressionista criou a famosa série das "Ninfeias"?',
    o: ['Claude Monet', 'Pierre-Auguste Renoir', 'Edgar Degas', 'Édouard Manet'],
    x: 'Uma tela de Monet, "Impressão, Nascer do Sol" (1872), acabou dando nome a todo o movimento impressionista.',
  },
  {
    id: 'art-13', cat: 'arte', nivel: 2,
    p: 'Qual instituto de arte contemporânea a céu aberto, com enormes jardins, fica em Brumadinho (MG)?',
    o: ['Inhotim', 'Pinacoteca', 'Instituto Tomie Ohtake', 'MAM'],
    x: 'Inhotim reúne obras de artistas do mundo todo em pavilhões espalhados por um grande jardim botânico.',
  },
  {
    id: 'art-14', cat: 'arte', nivel: 2,
    p: 'Em qual cidade aconteceu a Semana de Arte Moderna de 1922?',
    o: ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Recife'],
    x: 'O evento, no Theatro Municipal, reuniu nomes como Anita Malfatti, Mário de Andrade, Di Cavalcanti e Villa-Lobos.',
  },
  {
    id: 'art-15', cat: 'arte', nivel: 3,
    p: 'Qual artista brasileiro criou os "Parangolés", capas coloridas feitas para vestir e dançar?',
    o: ['Hélio Oiticica', 'Cildo Meireles', 'Lygia Pape', 'Waltercio Caldas'],
    x: 'Oiticica também criou a instalação "Tropicália" (1967), que acabou dando nome ao movimento musical.',
  },
  {
    id: 'art-16', cat: 'arte', nivel: 3,
    p: 'Qual artista brasileira criou os "Bichos", esculturas de metal com dobradiças para o público manipular?',
    o: ['Lygia Clark', 'Lygia Pape', 'Tomie Ohtake', 'Mira Schendel'],
    x: 'Os Bichos, do início dos anos 1960, convidavam o espectador a participar da obra, algo muito ousado para a época.',
  },
  {
    id: 'art-17', cat: 'arte', nivel: 3,
    p: 'Qual artista nascida no Japão começou a pintar aos 39 anos e virou referência da arte abstrata no Brasil?',
    o: ['Tomie Ohtake', 'Mira Schendel', 'Manabu Mabe', 'Yayoi Kusama'],
    x: 'Radicada em São Paulo, ela produziu até depois dos 100 anos, e um instituto com seu nome fica no bairro de Pinheiros.',
  },
  {
    id: 'art-18', cat: 'arte', nivel: 3,
    p: 'Qual pintor holandês criou "Moça com Brinco de Pérola"?',
    o: ['Johannes Vermeer', 'Rembrandt', 'Frans Hals', 'Jan Steen'],
    x: 'O quadro, de cerca de 1665, está no museu Mauritshuis, em Haia, e já inspirou um livro e um filme.',
  },

  // ——— Brasil ———
  {
    id: 'bra-01', cat: 'brasil', nivel: 1,
    p: 'Em que ano Brasília foi inaugurada como nova capital do Brasil?',
    o: ['1960', '1950', '1956', '1964'],
    x: 'A cidade foi erguida em menos de quatro anos, no governo de Juscelino Kubitschek, e inaugurada em 21 de abril.',
  },
  {
    id: 'bra-02', cat: 'brasil', nivel: 1,
    p: 'Qual é o maior bioma do Brasil em área?',
    o: ['Amazônia', 'Cerrado', 'Mata Atlântica', 'Caatinga'],
    x: 'O segundo maior é o Cerrado, chamado de "berço das águas" por abrigar nascentes de grandes rios brasileiros.',
  },
  {
    id: 'bra-03', cat: 'brasil', nivel: 1,
    p: 'Quantos estados o Brasil tem, além do Distrito Federal?',
    o: ['26', '27', '25', '24'],
    x: 'O estado mais novo é o Tocantins, criado pela Constituição de 1988 a partir do norte de Goiás.',
  },
  {
    id: 'bra-04', cat: 'brasil', nivel: 1,
    p: 'Qual rio, apelidado de "Velho Chico", corta cinco estados brasileiros?',
    o: ['São Francisco', 'Tocantins', 'Paraná', 'Parnaíba'],
    x: 'Ele nasce na Serra da Canastra (MG) e deságua no Oceano Atlântico, na divisa entre Alagoas e Sergipe.',
  },
  {
    id: 'bra-05', cat: 'brasil', nivel: 1,
    p: 'Qual cidade foi a primeira capital do Brasil?',
    o: ['Salvador', 'Rio de Janeiro', 'Recife', 'São Paulo'],
    x: 'Salvador foi a capital de 1549 a 1763, quando a sede do governo passou para o Rio de Janeiro.',
  },
  {
    id: 'bra-06', cat: 'brasil', nivel: 1,
    p: 'Qual inventor brasileiro voou com o 14-Bis em Paris, em 1906?',
    o: ['Santos Dumont', 'Bartolomeu de Gusmão', 'Augusto Severo', 'Landell de Moura'],
    x: 'Seu amigo Louis Cartier criou para ele um relógio de pulso, para que pudesse ver as horas sem soltar os comandos.',
  },
  {
    id: 'bra-07', cat: 'brasil', nivel: 1,
    p: 'Qual árvore deu nome ao Brasil?',
    o: ['Pau-brasil', 'Ipê-amarelo', 'Jequitibá', 'Araucária'],
    x: 'Sua madeira fornecia um corante vermelho muito valioso, e o nome vem de "brasa", por causa da cor.',
  },
  {
    id: 'bra-08', cat: 'brasil', nivel: 2,
    p: 'Qual é o ponto mais alto do Brasil?',
    o: ['Pico da Neblina', 'Pico da Bandeira', 'Monte Roraima', 'Pico das Agulhas Negras'],
    x: 'Com quase 3 mil metros de altitude, o pico fica no Amazonas, perto da fronteira com a Venezuela.',
  },
  {
    id: 'bra-09', cat: 'brasil', nivel: 2,
    p: 'Qual estado brasileiro tem o maior número de municípios?',
    o: ['Minas Gerais', 'São Paulo', 'Bahia', 'Rio Grande do Sul'],
    x: 'São 853 municípios mineiros, mais do que em qualquer outro estado do país.',
  },
  {
    id: 'bra-10', cat: 'brasil', nivel: 2,
    p: 'Com quantos países o Brasil faz fronteira?',
    o: ['10', '8', '9', '12'],
    x: 'Na América do Sul, só o Chile e o Equador não fazem fronteira com o Brasil.',
  },
  {
    id: 'bra-11', cat: 'brasil', nivel: 2,
    p: 'Às margens de qual riacho foi proclamada a Independência do Brasil, em 1822?',
    o: ['Ipiranga', 'Tietê', 'Anhangabaú', 'Tamanduateí'],
    x: 'O episódio aconteceu em 7 de setembro de 1822, em São Paulo, e ficou marcado pela frase "Independência ou Morte!".',
  },
  {
    id: 'bra-12', cat: 'brasil', nivel: 2,
    p: 'Qual é o menor estado brasileiro em área?',
    o: ['Sergipe', 'Alagoas', 'Espírito Santo', 'Rio de Janeiro'],
    x: 'Se contarmos o Distrito Federal, que não é um estado, ele é a menor unidade da federação.',
  },
  {
    id: 'bra-13', cat: 'brasil', nivel: 2,
    p: 'Qual tratado de 1494 dividiu as terras do Novo Mundo entre Portugal e Espanha?',
    o: ['Tratado de Tordesilhas', 'Tratado de Madri', 'Tratado de Santo Ildefonso', 'Tratado de Petrópolis'],
    x: 'A linha imaginária do tratado ficava a 370 léguas a oeste do arquipélago de Cabo Verde.',
  },
  {
    id: 'bra-14', cat: 'brasil', nivel: 2,
    p: 'Qual imperador governou o Brasil por quase 50 anos, até 1889?',
    o: ['Dom Pedro II', 'Dom Pedro I', 'Dom João VI', 'Dom Miguel'],
    x: 'Pedro II assumiu o trono aos 14 anos e era apaixonado por ciência, línguas e fotografia.',
  },
  {
    id: 'bra-15', cat: 'brasil', nivel: 3,
    p: 'Qual foi o primeiro parque nacional do Brasil, criado em 1937?',
    o: ['Itatiaia', 'Iguaçu', 'Serra dos Órgãos', 'Tijuca'],
    x: 'O parque fica entre o Rio de Janeiro e Minas Gerais e abriga o Pico das Agulhas Negras.',
  },
  {
    id: 'bra-16', cat: 'brasil', nivel: 3,
    p: 'Qual é o verdadeiro ponto extremo norte do Brasil?',
    o: ['Monte Caburaí', 'Foz do rio Oiapoque', 'Pico da Neblina', 'Cabo Orange'],
    x: 'A expressão "do Oiapoque ao Chuí" ficou famosa antes de se confirmar que o Caburaí, em Roraima, fica mais ao norte.',
  },
  {
    id: 'bra-17', cat: 'brasil', nivel: 3,
    p: 'Qual é considerada a primeira vila fundada no Brasil, em 1532?',
    o: ['São Vicente', 'Olinda', 'Salvador', 'São Paulo'],
    x: 'Ela foi fundada por Martim Afonso de Sousa, no litoral do atual estado de São Paulo.',
  },
  {
    id: 'bra-18', cat: 'brasil', nivel: 3,
    p: 'Qual atual estado brasileiro foi incorporado ao país em 1903, após um acordo com a Bolívia?',
    o: ['Acre', 'Rondônia', 'Roraima', 'Amapá'],
    x: 'O Tratado de Petrópolis incluiu o pagamento de 2 milhões de libras esterlinas e a construção da ferrovia Madeira-Mamoré.',
  },

  // ——— Ciência e natureza ———
  {
    id: 'cie-01', cat: 'ciencia', nivel: 1,
    p: 'Qual planeta é conhecido como "planeta vermelho"?',
    o: ['Marte', 'Júpiter', 'Vênus', 'Mercúrio'],
    x: 'A cor vem do óxido de ferro, uma espécie de ferrugem, presente na poeira e nas rochas marcianas.',
  },
  {
    id: 'cie-02', cat: 'ciencia', nivel: 1,
    p: 'Qual é o maior planeta do Sistema Solar?',
    o: ['Júpiter', 'Saturno', 'Netuno', 'Urano'],
    x: 'Júpiter é tão grande que caberiam mais de mil planetas Terra dentro dele.',
  },
  {
    id: 'cie-03', cat: 'ciencia', nivel: 1,
    p: 'Qual gás as plantas absorvem do ar para fazer fotossíntese?',
    o: ['Gás carbônico', 'Oxigênio', 'Nitrogênio', 'Hélio'],
    x: 'Com luz, água e gás carbônico, as plantas produzem açúcares e liberam oxigênio para a atmosfera.',
  },
  {
    id: 'cie-04', cat: 'ciencia', nivel: 1,
    p: 'Qual é o maior animal do mundo?',
    o: ['Baleia-azul', 'Elefante-africano', 'Tubarão-baleia', 'Cachalote'],
    x: 'A baleia-azul é considerada o maior animal que já existiu na Terra, maior até que os dinossauros conhecidos.',
  },
  {
    id: 'cie-05', cat: 'ciencia', nivel: 1,
    p: 'Qual é o maior roedor do mundo, muito comum em rios e lagos do Brasil?',
    o: ['Capivara', 'Paca', 'Cutia', 'Castor'],
    x: 'A capivara é ótima nadadora e consegue ficar alguns minutos debaixo d’água para fugir de predadores.',
  },
  {
    id: 'cie-06', cat: 'ciencia', nivel: 1,
    p: 'Em que ano o ser humano pisou na Lua pela primeira vez?',
    o: ['1969', '1961', '1965', '1972'],
    x: 'Na missão Apollo 11, Neil Armstrong foi o primeiro a pisar no solo lunar, seguido por Buzz Aldrin.',
  },
  {
    id: 'cie-07', cat: 'ciencia', nivel: 1,
    p: 'Qual cientista formulou a teoria da relatividade?',
    o: ['Albert Einstein', 'Isaac Newton', 'Galileu Galilei', 'Stephen Hawking'],
    x: 'A equação mais famosa da física, E = mc², mostra que massa e energia são equivalentes.',
  },
  {
    id: 'cie-08', cat: 'ciencia', nivel: 2,
    p: 'Qual cientista brasileiro descreveu, em 1909, o parasita, o inseto transmissor e a doença que leva seu nome?',
    o: ['Carlos Chagas', 'Oswaldo Cruz', 'Vital Brazil', 'Adolfo Lutz'],
    x: 'Descrever sozinho o agente, o transmissor (o barbeiro) e a doença foi um feito raríssimo na história da medicina.',
  },
  {
    id: 'cie-09', cat: 'ciencia', nivel: 2,
    p: 'Qual cientista brasileiro criou soros contra picadas de cobra no Instituto Butantan?',
    o: ['Vital Brazil', 'Carlos Chagas', 'Oswaldo Cruz', 'Emílio Ribas'],
    x: 'Ele descobriu que cada tipo de veneno exige um soro específico: o de jararaca não serve para cascavel, por exemplo.',
  },
  {
    id: 'cie-10', cat: 'ciencia', nivel: 2,
    p: 'Qual é o símbolo químico do ouro?',
    o: ['Au', 'Ag', 'Or', 'Go'],
    x: 'Au vem do latim "aurum". Já a prata, Ag, vem de "argentum", palavra que deu nome à Argentina.',
  },
  {
    id: 'cie-11', cat: 'ciencia', nivel: 2,
    p: 'Qual é a estrela mais próxima da Terra?',
    o: ['O Sol', 'Proxima Centauri', 'Sirius', 'Estrela Polar'],
    x: 'Depois do Sol, a estrela mais próxima é Proxima Centauri, a cerca de 4,2 anos-luz de distância.',
  },
  {
    id: 'cie-12', cat: 'ciencia', nivel: 2,
    p: 'Qual cientista nascida na Polônia ganhou dois prêmios Nobel, em Física e em Química?',
    o: ['Marie Curie', 'Rosalind Franklin', 'Lise Meitner', 'Irène Joliot-Curie'],
    x: 'Ela foi a primeira mulher a ganhar um Nobel, o de Física, em 1903. O de Química veio em 1911.',
  },
  {
    id: 'cie-13', cat: 'ciencia', nivel: 2,
    p: 'Quem descobriu a penicilina, em 1928?',
    o: ['Alexander Fleming', 'Louis Pasteur', 'Robert Koch', 'Edward Jenner'],
    x: 'Ao voltar de férias, ele notou que um mofo havia matado as bactérias de uma placa esquecida no laboratório.',
  },
  {
    id: 'cie-14', cat: 'ciencia', nivel: 2,
    p: 'Qual ave de pescoço preto, com uma faixa vermelha na base, é o símbolo do Pantanal?',
    o: ['Tuiuiú', 'Seriema', 'Tucano', 'Socó'],
    x: 'O tuiuiú, também chamado de jaburu, é uma grande cegonha que pode passar dos 2 metros de asa a asa.',
  },
  {
    id: 'cie-15', cat: 'ciencia', nivel: 3,
    p: 'Qual físico brasileiro participou da descoberta do méson pi, em 1947?',
    o: ['César Lattes', 'Mário Schenberg', 'José Leite Lopes', 'Marcelo Gleiser'],
    x: 'A Plataforma Lattes, que reúne os currículos dos pesquisadores do Brasil, recebeu esse nome em sua homenagem.',
  },
  {
    id: 'cie-16', cat: 'ciencia', nivel: 3,
    p: 'Qual é a maior lua do Sistema Solar?',
    o: ['Ganimedes', 'Titã', 'Europa', 'Lua'],
    x: 'Ganimedes, que orbita Júpiter, é maior até que o planeta Mercúrio.',
  },
  {
    id: 'cie-17', cat: 'ciencia', nivel: 3,
    p: 'Qual é o planeta mais quente do Sistema Solar?',
    o: ['Vênus', 'Mercúrio', 'Marte', 'Júpiter'],
    x: 'Mercúrio fica mais perto do Sol, mas a atmosfera densa de Vênus prende o calor e deixa a superfície acima de 450 °C.',
  },
  {
    id: 'cie-18', cat: 'ciencia', nivel: 3,
    p: 'Quantos cromossomos tem uma célula humana comum?',
    o: ['46', '23', '44', '48'],
    x: 'São 23 pares. Chimpanzés e outros grandes macacos têm 48 cromossomos.',
  },
];
