// Pauta das Matérias históricas e curiosidades: os assuntos de cada tema e o
// formato da matéria.
//
// Cada assunto é um verbete da Wikipédia em português — fonte gratuita, de
// licença aberta (CC BY-SA) e com referências. A plataforma não copia o
// verbete: monta uma matéria no formato dela (dossiê, perfil, linha do tempo,
// curiosidades), com imagens do Wikimedia Commons creditadas, vídeo de canal
// oficial e as fontes no fim. Só entram assuntos desta lista — nada de texto
// de origem desconhecida.

import type { CategorySlug } from './data';

export type FormatoDeMateria = 'dossie' | 'perfil' | 'linha-do-tempo' | 'curiosidades';

export interface Pauta {
  /** Título do verbete na Wikipédia em português. */
  verbete: string;
  formato: FormatoDeMateria;
}

export const FORMATOS: Record<FormatoDeMateria, { rotulo: string; apoio: string }> = {
  dossie: { rotulo: 'Dossiê', apoio: 'A história completa, do começo ao agora.' },
  perfil: { rotulo: 'Perfil', apoio: 'Quem é, de onde veio e o que deixou.' },
  'linha-do-tempo': { rotulo: 'Linha do tempo', apoio: 'Os marcos, ano a ano.' },
  curiosidades: { rotulo: 'Curiosidades', apoio: 'O que pouca gente sabe.' },
};

const p = (verbete: string, formato: FormatoDeMateria): Pauta => ({ verbete, formato });

export const PAUTA: Record<CategorySlug, Pauta[]> = {
  moda: [
    p('Alta-costura', 'dossie'),
    p('Coco Chanel', 'perfil'),
    p('Moda sustentável', 'dossie'),
    p('Moda do hip hop', 'curiosidades'),
    p('Zuzu Angel', 'perfil'),
    p('Jeans', 'linha-do-tempo'),
    p('São Paulo Fashion Week', 'dossie'),
    p('Minissaia', 'curiosidades'),
    p('Alexander McQueen', 'perfil'),
    p('Havaianas', 'curiosidades'),
    p('Yves Saint Laurent', 'perfil'),
    // Moda brasileira: quem fez, o que se veste e de onde vem.
    p('Clodovil Hernandes', 'perfil'),
    p('Alexandre Herchcovitch', 'perfil'),
    p('Ronaldo Fraga', 'perfil'),
    p('Dener Pamplona', 'perfil'),
    p('Gisele Bündchen', 'perfil'),
    p('Costanza Pascolato', 'perfil'),
    p('Lenny Niemeyer', 'perfil'),
    p('Glória Coelho', 'perfil'),
    p('Carlos Miele', 'perfil'),
    p('Cia. Hering', 'linha-do-tempo'),
    p('Chita (tecido)', 'curiosidades'),
    p('Renda de bilros', 'curiosidades'),
    // Clássicos do mundo.
    p('Christian Dior', 'perfil'),
    p('Karl Lagerfeld', 'perfil'),
    p('Vivienne Westwood', 'perfil'),
    p('Giorgio Armani', 'perfil'),
    p('História da moda', 'linha-do-tempo'),
    p('Biquíni', 'linha-do-tempo'),
    p('Salto-alto', 'linha-do-tempo'),
    p('Tênis (vestuário)', 'linha-do-tempo'),
    p('Espartilho', 'curiosidades'),
    p('Vogue (revista)', 'linha-do-tempo'),
    p('Fast fashion', 'dossie'),
  ],
  tecnologia: [
    p('Inteligência artificial', 'dossie'),
    p('Alan Turing', 'perfil'),
    p('Internet', 'linha-do-tempo'),
    p('Software livre', 'dossie'),
    p('Computação quântica', 'curiosidades'),
    p('Linux', 'linha-do-tempo'),
    p('Ada Lovelace', 'perfil'),
    p('World Wide Web', 'dossie'),
    p('Smartphone', 'curiosidades'),
    p('Criptografia', 'dossie'),
    // Tecnologia feita no Brasil.
    p('Santos Dumont', 'perfil'),
    p('Roberto Landell de Moura', 'perfil'),
    p('Marcos Pontes', 'perfil'),
    p('Johanna Döbereiner', 'perfil'),
    p('Urna eletrônica (Brasil)', 'curiosidades'),
    p('Pix', 'curiosidades'),
    p('Lua (linguagem de programação)', 'curiosidades'),
    p('Orkut', 'curiosidades'),
    p('Embraer', 'linha-do-tempo'),
    p('Internet no Brasil', 'linha-do-tempo'),
    p('Televisão no Brasil', 'linha-do-tempo'),
    p('Programa espacial brasileiro', 'dossie'),
    p('Centro Espacial de Alcântara', 'curiosidades'),
    p('Satélite Sino-Brasileiro de Recursos Terrestres', 'curiosidades'),
    p('Empresa Brasileira de Pesquisa Agropecuária', 'dossie'),
    p('Instituto Tecnológico de Aeronáutica', 'dossie'),
    // Clássicos do mundo.
    p('Steve Jobs', 'perfil'),
    p('Grace Hopper', 'perfil'),
    p('Tim Berners-Lee', 'perfil'),
    p('Hedy Lamarr', 'perfil'),
    p('Transístor', 'linha-do-tempo'),
    p('ENIAC', 'curiosidades'),
    p('Impressão 3D', 'curiosidades'),
  ],
  musica: [
    p('Bossa nova', 'dossie'),
    p('Tropicália', 'dossie'),
    p('Samba', 'linha-do-tempo'),
    p('Elis Regina', 'perfil'),
    p('MPB', 'dossie'),
    p('Disco de vinil', 'curiosidades'),
    p('Hip-hop', 'linha-do-tempo'),
    p('Tom Jobim', 'perfil'),
    p('Chiquinha Gonzaga', 'perfil'),
    p('Rock in Rio', 'curiosidades'),
    // Música brasileira.
    p('Luiz Gonzaga', 'perfil'),
    p('Pixinguinha', 'perfil'),
    p('Cartola (cantor)', 'perfil'),
    p('Heitor Villa-Lobos', 'perfil'),
    p('Rita Lee', 'perfil'),
    p("Racionais MC's", 'perfil'),
    p('Choro', 'linha-do-tempo'),
    p('Clube da Esquina', 'dossie'),
    p('Jovem Guarda', 'curiosidades'),
    p('Manguebeat', 'dossie'),
    p('Funk carioca', 'linha-do-tempo'),
    p('Música sertaneja', 'linha-do-tempo'),
    // Clássicos do mundo.
    p('The Beatles', 'perfil'),
    p('Michael Jackson', 'perfil'),
    p('Bob Marley', 'perfil'),
    p('Wolfgang Amadeus Mozart', 'perfil'),
    p('Jazz', 'linha-do-tempo'),
    p('Blues', 'linha-do-tempo'),
    p('Rock and roll', 'linha-do-tempo'),
    p('Reggae', 'curiosidades'),
    p('Música eletrônica', 'dossie'),
    p('Festival de Woodstock', 'curiosidades'),
  ],
  cultura: [
    p('Semana de Arte Moderna', 'dossie'),
    p('Tarsila do Amaral', 'perfil'),
    p('Literatura de cordel', 'curiosidades'),
    p('Museu do Ipiranga', 'linha-do-tempo'),
    p('Carnaval do Brasil', 'dossie'),
    p('Capoeira', 'linha-do-tempo'),
    p('Oscar Niemeyer', 'perfil'),
    p('Teatro Oficina', 'curiosidades'),
    // Cultura brasileira: festas, fé, arquitetura e patrimônio.
    p('Bumba meu boi', 'curiosidades'),
    p('Festival Folclórico de Parintins', 'curiosidades'),
    p('Festa junina', 'linha-do-tempo'),
    p('Círio de Nazaré', 'curiosidades'),
    p('Frevo', 'curiosidades'),
    p('Candomblé', 'dossie'),
    p('Movimento antropofágico', 'dossie'),
    p('Cristo Redentor', 'linha-do-tempo'),
    p('Museu Nacional (Rio de Janeiro)', 'linha-do-tempo'),
    p('Lina Bo Bardi', 'perfil'),
    p('Roberto Burle Marx', 'perfil'),
    p('Abdias do Nascimento', 'perfil'),
    // Clássicos do mundo.
    p('Renascimento', 'dossie'),
    p('Bauhaus', 'dossie'),
    p('Antoni Gaudí', 'perfil'),
    p('Museu do Louvre', 'curiosidades'),
    p('Coliseu', 'linha-do-tempo'),
    p('Taj Mahal', 'curiosidades'),
    p('Teatro na Grécia Antiga', 'dossie'),
    p("Commedia dell'arte", 'curiosidades'),
    p('Kabuki', 'curiosidades'),
    p('Ópera', 'linha-do-tempo'),
    p('Tango', 'linha-do-tempo'),
    p('Flamenco', 'curiosidades'),
    p('Dia dos Mortos', 'curiosidades'),
  ],
  esporte: [
    p('Copa do Mundo FIFA', 'linha-do-tempo'),
    p('Pelé', 'perfil'),
    p('Marta (futebolista)', 'perfil'),
    p('Ayrton Senna', 'perfil'),
    p('Jogos Olímpicos', 'dossie'),
    p('Estádio Jornalista Mário Filho', 'curiosidades'),
    p('Voleibol de praia', 'dossie'),
    p('Skate', 'curiosidades'),
    p('Rebeca Andrade', 'perfil'),
    // Esporte brasileiro.
    p('Seleção Brasileira de Futebol', 'linha-do-tempo'),
    p('Seleção Brasileira de Voleibol Masculino', 'dossie'),
    p('Seleção Brasileira de Voleibol Feminino', 'dossie'),
    p('Garrincha', 'perfil'),
    p('Ronaldo Nazário', 'perfil'),
    p('Gustavo Kuerten', 'perfil'),
    p('Maria Esther Bueno', 'perfil'),
    p('Oscar Schmidt', 'perfil'),
    p('Hortência Marcari', 'perfil'),
    p('Adhemar Ferreira da Silva', 'perfil'),
    p('Emerson Fittipaldi', 'perfil'),
    p('Gabriel Medina', 'perfil'),
    p('Maracanaço', 'curiosidades'),
    p('Democracia Corinthiana', 'curiosidades'),
    p('Jiu-jítsu brasileiro', 'linha-do-tempo'),
    // Clássicos do mundo.
    p('Michael Jordan', 'perfil'),
    p('Muhammad Ali', 'perfil'),
    p('Usain Bolt', 'perfil'),
    p('Serena Williams', 'perfil'),
    p('Nadia Comăneci', 'perfil'),
    p('Diego Maradona', 'perfil'),
    p('Fórmula 1', 'linha-do-tempo'),
    p('Maratona', 'linha-do-tempo'),
    p('Basquetebol', 'linha-do-tempo'),
    p('Futsal', 'curiosidades'),
    p('Surfe', 'dossie'),
  ],
  cinema: [
    p('Cinema Novo', 'dossie'),
    p('Glauber Rocha', 'perfil'),
    p('Central do Brasil (filme)', 'curiosidades'),
    p('Fernanda Montenegro', 'perfil'),
    p('Óscar', 'linha-do-tempo'),
    p('Cidade de Deus (filme)', 'curiosidades'),
    p('Charlie Chaplin', 'perfil'),
    p('Filme mudo', 'dossie'),
    p('Animação', 'linha-do-tempo'),
    // Cinema e TV do Brasil.
    p('Grande Otelo', 'perfil'),
    p('Mazzaropi', 'perfil'),
    p('Walter Salles', 'perfil'),
    p('Eduardo Coutinho', 'perfil'),
    p('Chanchada', 'curiosidades'),
    p('Companhia Cinematográfica Vera Cruz', 'linha-do-tempo'),
    p('Cinema marginal', 'dossie'),
    p('Telenovela', 'linha-do-tempo'),
    p('O Pagador de Promessas', 'curiosidades'),
    p('Pixote, a Lei do Mais Fraco', 'curiosidades'),
    p('O Auto da Compadecida (filme)', 'curiosidades'),
    p('Tropa de Elite (filme)', 'curiosidades'),
    p('Bacurau (filme)', 'curiosidades'),
    p('Ainda Estou Aqui (filme de 2024)', 'curiosidades'),
    // Clássicos do mundo.
    p('Auguste e Louis Lumière', 'perfil'),
    p('Georges Méliès', 'perfil'),
    p('Alfred Hitchcock', 'perfil'),
    p('Akira Kurosawa', 'perfil'),
    p('Stanley Kubrick', 'perfil'),
    p('Citizen Kane', 'curiosidades'),
    p('Neorrealismo italiano', 'dossie'),
    p('Nouvelle vague', 'dossie'),
    p('Studio Ghibli', 'curiosidades'),
    p('Star Wars', 'curiosidades'),
  ],
  livros: [
    p('Machado de Assis', 'perfil'),
    p('Clarice Lispector', 'perfil'),
    p('Carlos Drummond de Andrade', 'perfil'),
    p('Modernismo no Brasil', 'dossie'),
    p('Dom Casmurro', 'curiosidades'),
    p('Grande Sertão: Veredas', 'curiosidades'),
    p('Conceição Evaristo', 'perfil'),
    p('Monteiro Lobato', 'perfil'),
    p('Prensa móvel', 'linha-do-tempo'),
    // Literatura brasileira.
    p('Jorge Amado', 'perfil'),
    p('Graciliano Ramos', 'perfil'),
    p('Rachel de Queiroz', 'perfil'),
    p('Cecília Meireles', 'perfil'),
    p('Lima Barreto (escritor)', 'perfil'),
    p('Carolina Maria de Jesus', 'perfil'),
    p('Ariano Suassuna', 'perfil'),
    p('Macunaíma', 'curiosidades'),
    p('Os Sertões', 'dossie'),
    p('Memórias Póstumas de Brás Cubas', 'curiosidades'),
    p('Academia Brasileira de Letras', 'linha-do-tempo'),
    // Clássicos do mundo.
    p('William Shakespeare', 'perfil'),
    p('Jane Austen', 'perfil'),
    p('Franz Kafka', 'perfil'),
    p('Fernando Pessoa', 'perfil'),
    p('José Saramago', 'perfil'),
    p('Gabriel García Márquez', 'perfil'),
    p('Dom Quixote', 'curiosidades'),
    p('Cem Anos de Solidão', 'curiosidades'),
    p('1984 (livro)', 'curiosidades'),
    p('Biblioteca de Alexandria', 'curiosidades'),
    p('Livro', 'linha-do-tempo'),
    p('Prêmio Nobel de Literatura', 'linha-do-tempo'),
  ],
  gastronomia: [
    p('Feijoada', 'curiosidades'),
    p('Pão de queijo', 'curiosidades'),
    p('Culinária do Brasil', 'dossie'),
    p('Café', 'linha-do-tempo'),
    p('Açaí', 'curiosidades'),
    p('Brigadeiro (doce)', 'curiosidades'),
    p('Moqueca', 'dossie'),
    p('Cachaça', 'linha-do-tempo'),
    p('Mandioca', 'dossie'),
    // Cozinha brasileira: pratos, bebidas e quem cozinha.
    p('Acarajé', 'curiosidades'),
    p('Tacacá', 'curiosidades'),
    p('Pato no tucupi', 'curiosidades'),
    p('Tapioca', 'curiosidades'),
    p('Coxinha', 'curiosidades'),
    p('Pastel (culinária)', 'curiosidades'),
    p('Churrasco', 'linha-do-tempo'),
    p('Caipirinha', 'curiosidades'),
    p('Guaraná', 'curiosidades'),
    p('Culinária da Bahia', 'dossie'),
    p('Culinária de Minas Gerais', 'dossie'),
    p('Alex Atala', 'perfil'),
    p('Paola Carosella', 'perfil'),
    // Clássicos do mundo.
    p('Auguste Escoffier', 'perfil'),
    p('Paul Bocuse', 'perfil'),
    p('Julia Child', 'perfil'),
    p('Chocolate', 'linha-do-tempo'),
    p('Pizza', 'linha-do-tempo'),
    p('Sushi', 'curiosidades'),
    p('Queijo', 'dossie'),
    p('Vinho', 'dossie'),
    p('Cerveja', 'linha-do-tempo'),
    p('Especiaria', 'linha-do-tempo'),
    p('Gastronomia molecular', 'curiosidades'),
  ],
  viagem: [
    p('Fernando de Noronha', 'dossie'),
    p('Parque Nacional dos Lençóis Maranhenses', 'curiosidades'),
    p('Pantanal', 'dossie'),
    p('Chapada Diamantina', 'curiosidades'),
    p('Cataratas do Iguaçu', 'curiosidades'),
    p('Ouro Preto', 'linha-do-tempo'),
    p('Amazônia', 'dossie'),
    p('Bonito (Mato Grosso do Sul)', 'curiosidades'),
    // Brasil.
    p('Parque Estadual do Jalapão', 'curiosidades'),
    p('Parque Nacional da Chapada dos Veadeiros', 'curiosidades'),
    p('Parque Nacional Serra da Capivara', 'dossie'),
    p('Parque Nacional de Jericoacoara', 'curiosidades'),
    p('Parque Nacional Marinho dos Abrolhos', 'curiosidades'),
    p('Monte Roraima', 'curiosidades'),
    p('Ilha Grande (Angra dos Reis)', 'curiosidades'),
    p('Paraty', 'linha-do-tempo'),
    p('Olinda', 'linha-do-tempo'),
    p('Centro Histórico de Salvador', 'linha-do-tempo'),
    // Mundo.
    p('Machu Picchu', 'curiosidades'),
    p('Deserto de Atacama', 'curiosidades'),
    p('Salar de Uyuni', 'curiosidades'),
    p('Patagónia', 'dossie'),
    p('Galápagos', 'curiosidades'),
    p('Chichén Itzá', 'curiosidades'),
    p('Grand Canyon', 'curiosidades'),
    p('Caminhos de Santiago', 'dossie'),
    p('Lisboa', 'linha-do-tempo'),
    p('Veneza', 'linha-do-tempo'),
    p('Santorini', 'curiosidades'),
    p('Petra', 'curiosidades'),
    p('Grande Muralha da China', 'linha-do-tempo'),
    p('Quioto', 'linha-do-tempo'),
  ],
  games: [
    p('Jogo eletrônico', 'linha-do-tempo'),
    p('Nintendo', 'linha-do-tempo'),
    p('Esporte eletrônico', 'dossie'),
    p('The Legend of Zelda', 'curiosidades'),
    p('Minecraft', 'curiosidades'),
    p('PlayStation', 'linha-do-tempo'),
    p('Pac-Man', 'curiosidades'),
    p('Tetris', 'curiosidades'),
    // Games no Brasil: consoles da Tectoy, jogos daqui e a cena.
    p('Jogos eletrônicos no Brasil', 'linha-do-tempo'),
    p('Tectoy', 'perfil'),
    p('Master System', 'linha-do-tempo'),
    p('Mega Drive', 'linha-do-tempo'),
    p('Zeebo', 'curiosidades'),
    p('Polystation', 'curiosidades'),
    p('Mônica no Castelo do Dragão', 'curiosidades'),
    p('Top Gear (jogo eletrônico)', 'curiosidades'),
    p('Horizon Chase', 'curiosidades'),
    p('Dandara (jogo eletrônico)', 'curiosidades'),
    p('Free Fire', 'curiosidades'),
    p('Campeonato Brasileiro de League of Legends', 'dossie'),
    p('Brasil Game Show', 'curiosidades'),
    p('Arcade', 'curiosidades'),
    p('LAN house', 'curiosidades'),
    // Clássicos do mundo.
    p('Shigeru Miyamoto', 'perfil'),
    p('Magnavox Odyssey', 'curiosidades'),
    p('Atari 2600', 'linha-do-tempo'),
    p('Space Invaders', 'curiosidades'),
    p('Super Mario Bros.', 'curiosidades'),
    p('Sonic the Hedgehog', 'linha-do-tempo'),
    p('Street Fighter II', 'curiosidades'),
    p('Mortal Kombat', 'curiosidades'),
    p('Doom (jogo eletrônico de 1993)', 'curiosidades'),
    p('Pokémon', 'curiosidades'),
    p('Counter-Strike', 'curiosidades'),
  ],
  'bem-estar': [
    p('Meditação', 'dossie'),
    p('Sono', 'curiosidades'),
    p('Ioga', 'linha-do-tempo'),
    p('Atividade física', 'dossie'),
    p('Saúde mental', 'dossie'),
    p('Caminhada', 'curiosidades'),
    // Saúde pública e cuidado no Brasil.
    p('Nise da Silveira', 'perfil'),
    p('Oswaldo Cruz', 'perfil'),
    p('Carlos Chagas', 'perfil'),
    p('Vital Brazil', 'perfil'),
    p('Adolfo Lutz', 'perfil'),
    p('Zilda Arns', 'perfil'),
    p('Sistema Único de Saúde', 'dossie'),
    p('Programa Nacional de Imunizações', 'linha-do-tempo'),
    p('Zé Gotinha', 'curiosidades'),
    p('Revolta da Vacina', 'curiosidades'),
    p('Instituto Butantan', 'linha-do-tempo'),
    p('Reforma psiquiátrica no Brasil', 'linha-do-tempo'),
    p('Alimentos ultraprocessados', 'dossie'),
    // Corpo e mente.
    p('Atenção plena', 'curiosidades'),
    p('Estresse', 'curiosidades'),
    p('Síndrome de burnout', 'dossie'),
    p('Ritmo circadiano', 'curiosidades'),
    p('Microbiota intestinal', 'curiosidades'),
    p('Nutrição', 'dossie'),
    p('Dieta mediterrânica', 'curiosidades'),
    p('Corrida', 'dossie'),
    p('Musculação', 'linha-do-tempo'),
    p('Alongamento', 'curiosidades'),
    p('Pilates', 'linha-do-tempo'),
    p('Tai chi chuan', 'curiosidades'),
    p('Florence Nightingale', 'perfil'),
    p('Penicilina', 'linha-do-tempo'),
  ],
  arte: [
    p('Fotografia', 'linha-do-tempo'),
    p('Sebastião Salgado', 'perfil'),
    p('Candido Portinari', 'perfil'),
    p('Grafito', 'dossie'),
    p('Arte digital', 'dossie'),
    p('Frida Kahlo', 'perfil'),
    p('Vincent van Gogh', 'perfil'),
    p('Os Gêmeos', 'perfil'),
    p('Impressionismo', 'linha-do-tempo'),
    // Arte brasileira.
    p('Aleijadinho', 'perfil'),
    p('Anita Malfatti', 'perfil'),
    p('Di Cavalcanti', 'perfil'),
    p('Alfredo Volpi', 'perfil'),
    p('Djanira', 'perfil'),
    p('Tomie Ohtake', 'perfil'),
    p('Hélio Oiticica', 'perfil'),
    p('Lygia Clark', 'perfil'),
    p('Bispo do Rosário', 'perfil'),
    p('Vik Muniz', 'perfil'),
    p('Pierre Verger', 'perfil'),
    p('Abaporu', 'curiosidades'),
    p('Arte marajoara', 'curiosidades'),
    p('Bienal Internacional de Arte de São Paulo', 'linha-do-tempo'),
    p('Museu de Arte de São Paulo', 'curiosidades'),
    p('Instituto Inhotim', 'curiosidades'),
    // Clássicos do mundo.
    p('Arte rupestre', 'linha-do-tempo'),
    p('Leonardo da Vinci', 'perfil'),
    p('Mona Lisa', 'curiosidades'),
    p('Michelangelo', 'perfil'),
    p('Rembrandt', 'perfil'),
    p('Claude Monet', 'perfil'),
    p('Pablo Picasso', 'perfil'),
    p('Surrealismo', 'dossie'),
    p('Pop art', 'dossie'),
    p('Andy Warhol', 'perfil'),
    p('Jean-Michel Basquiat', 'perfil'),
  ],
};

/**
 * Palavras que puxam um fato do "Hoje na história" para o tema. Casam no
 * começo da palavra, então radicais valem ("olímpic" pega olímpico/olímpica).
 */
export const TERMOS_DA_HISTORIA: Record<CategorySlug, string[]> = {
  moda: ['moda', 'estilista', 'costureir', 'desfile', 'grife', 'vestido', 'fashion', 'maison'],
  tecnologia: ['computador', 'internet', 'software', 'satélite', 'tecnologi', 'microsoft', 'apple', 'google', 'inteligência artificial', 'telefone', 'foguete', 'transistor'],
  musica: ['música', 'músic', 'cantor', 'banda', 'álbum', 'compositor', 'canção', 'orquestra', 'samba', 'ópera', 'beatles'],
  cultura: ['museu', 'teatro', 'patrimônio', 'arquitet', 'carnaval', 'cultura', 'biblioteca', 'unesco'],
  esporte: ['futebol', 'copa do mundo', 'olímpic', 'campeonato', 'fórmula 1', 'atleta', 'estádio', 'tenista', 'voleibol', 'basquete', 'maratona'],
  cinema: ['filme', 'cinema', 'cineasta', 'ator ', 'atriz', 'oscar', 'hollywood', 'estreia'],
  livros: ['livro', 'romance', 'escritor', 'poeta', 'poema', 'literatura', 'literári', 'publicad', 'nobel de literatura'],
  gastronomia: ['culinári', 'restaurante', 'alimento', 'comida', 'café', 'vinho', 'cerveja', 'chocolate', 'chef'],
  viagem: ['parque nacional', 'turismo', 'turista', 'patrimônio mundial', 'expedição', 'navegador', 'aeroporto', 'voo ', 'cataratas'],
  games: ['jogo eletrônico', 'jogos eletrônicos', 'videogame', 'nintendo', 'playstation', 'xbox', 'sega', 'atari', 'console'],
  'bem-estar': ['saúde', 'medicina', 'vacina', 'hospital', 'médic', 'doença', 'penicilina', 'epidemia'],
  arte: ['pintor', 'pintura', 'escultor', 'escultura', 'fotografia', 'fotógraf', 'exposição', 'artista', 'museu'],
};

/** "Coco Chanel" → "coco-chanel"; é o endereço da matéria. */
export function slugDaPauta(verbete: string): string {
  return verbete
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function pautaPorSlug(tema: CategorySlug, slug: string): Pauta | null {
  return PAUTA[tema]?.find((x) => slugDaPauta(x.verbete) === slug) ?? null;
}
