-- nexo.social — coleção embutida dos itens exclusivos (gerado a partir de
-- public/colecao/<tema>/<fundos|adesivos|bottons>). Os arquivos ficam no
-- próprio site; o catálogo e as concessões, no banco (db/exclusivos.sql).
-- O superadministrador monta o kit e envia em /admin → Exclusivos.
-- Pode rodar mais de uma vez: atualiza nome, tema e edição sem mexer em quem já recebeu.

INSERT INTO exclusive_assets (title, kind, collection, edition, image_path, thumb_path, sort_order)
VALUES
  ('Linkin Park · Discografia', 'wallpaper', 'Linkin Park', 'Discografia', '/colecao/linkin-park/fundos/discografia.webp', '/colecao/linkin-park/fundos/discografia-mini.webp', 1),
  ('Linkin Park · Edição especial', 'wallpaper', 'Linkin Park', 'Edição especial', '/colecao/linkin-park/fundos/edicao-especial.webp', '/colecao/linkin-park/fundos/edicao-especial-mini.webp', 2),
  ('System of a Down · Discografia', 'wallpaper', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/fundos/discografia.webp', '/colecao/system-of-a-down/fundos/discografia-mini.webp', 3),
  ('System of a Down · Edição especial', 'wallpaper', 'System of a Down', 'Edição especial', '/colecao/system-of-a-down/fundos/edicao-especial.webp', '/colecao/system-of-a-down/fundos/edicao-especial-mini.webp', 4),
  ('Twenty One Pilots · Breach', 'wallpaper', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/fundos/breach.webp', '/colecao/twenty-one-pilots/fundos/breach-mini.webp', 5),
  ('DRAP · Inauguração · Edição Rock', 'wallpaper', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/fundos/rock.webp', '/colecao/drap-inauguracao/fundos/rock-mini.webp', 6),
  ('DRAP · Inauguração · Edição Medieval', 'wallpaper', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/fundos/medieval.webp', '/colecao/drap-inauguracao/fundos/medieval-mini.webp', 7),
  ('Nexo Social · Inauguração · Edição Pop', 'wallpaper', 'Nexo Social · Inauguração', 'Edição Pop', '/colecao/nexo-social-inauguracao/fundos/pop.webp', '/colecao/nexo-social-inauguracao/fundos/pop-mini.webp', 8),
  ('Nexo Social · Inauguração · Edição Medieval', 'wallpaper', 'Nexo Social · Inauguração', 'Edição Medieval', '/colecao/nexo-social-inauguracao/fundos/medieval.webp', '/colecao/nexo-social-inauguracao/fundos/medieval-mini.webp', 9),
  ('Hybrid Theory', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-01.webp', NULL, 10),
  ('Meteora', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-02.webp', NULL, 11),
  ('Minutes to Midnight', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-03.webp', NULL, 12),
  ('A Thousand Suns', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-04.webp', NULL, 13),
  ('Living Things', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-05.webp', NULL, 14),
  ('The Hunting Party', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-06.webp', NULL, 15),
  ('One More Light', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-07.webp', NULL, 16),
  ('Símbolo', 'sticker', 'Linkin Park', 'Discografia', '/colecao/linkin-park/adesivos/discografia-08.webp', NULL, 17),
  ('Hybrid Theory', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-01.webp', NULL, 18),
  ('Meteora', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-02.webp', NULL, 19),
  ('Minutes to Midnight', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-03.webp', NULL, 20),
  ('A Thousand Suns', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-04.webp', NULL, 21),
  ('Living Things', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-05.webp', NULL, 22),
  ('The Hunting Party', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-06.webp', NULL, 23),
  ('One More Light', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-07.webp', NULL, 24),
  ('Símbolo', 'button', 'Linkin Park', 'Discografia', '/colecao/linkin-park/bottons/discografia-08.webp', NULL, 25),
  ('Linkin Park', 'sticker', 'Linkin Park', 'Edição especial', '/colecao/linkin-park/adesivos/edicao-especial-01.webp', NULL, 26),
  ('Anjo acorrentado', 'sticker', 'Linkin Park', 'Edição especial', '/colecao/linkin-park/adesivos/edicao-especial-02.webp', NULL, 27),
  ('Caixa de som', 'sticker', 'Linkin Park', 'Edição especial', '/colecao/linkin-park/adesivos/edicao-especial-03.webp', NULL, 28),
  ('Microfone acorrentado', 'sticker', 'Linkin Park', 'Edição especial', '/colecao/linkin-park/adesivos/edicao-especial-04.webp', NULL, 29),
  ('Estilhaços', 'sticker', 'Linkin Park', 'Edição especial', '/colecao/linkin-park/adesivos/edicao-especial-05.webp', NULL, 30),
  ('Edição especial', 'sticker', 'Linkin Park', 'Edição especial', '/colecao/linkin-park/adesivos/edicao-especial-06.webp', NULL, 31),
  ('System of a Down', 'sticker', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/adesivos/discografia-01.webp', NULL, 32),
  ('Toxicity', 'sticker', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/adesivos/discografia-02.webp', NULL, 33),
  ('Steal This Album!', 'sticker', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/adesivos/discografia-03.webp', NULL, 34),
  ('Mezmerize', 'sticker', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/adesivos/discografia-04.webp', NULL, 35),
  ('Hypnotize', 'sticker', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/adesivos/discografia-05.webp', NULL, 36),
  ('Protesto', 'sticker', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/adesivos/discografia-06.webp', NULL, 37),
  ('System of a Down', 'button', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/bottons/discografia-01.webp', NULL, 38),
  ('Toxicity', 'button', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/bottons/discografia-02.webp', NULL, 39),
  ('Steal This Album!', 'button', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/bottons/discografia-03.webp', NULL, 40),
  ('Mezmerize', 'button', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/bottons/discografia-04.webp', NULL, 41),
  ('Hypnotize', 'button', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/bottons/discografia-05.webp', NULL, 42),
  ('Coletânea', 'button', 'System of a Down', 'Discografia', '/colecao/system-of-a-down/bottons/discografia-06.webp', NULL, 43),
  ('System of a Down', 'sticker', 'System of a Down', 'Edição especial', '/colecao/system-of-a-down/adesivos/edicao-especial-01.webp', NULL, 44),
  ('Megafone', 'sticker', 'System of a Down', 'Edição especial', '/colecao/system-of-a-down/adesivos/edicao-especial-02.webp', NULL, 45),
  ('Olho e telas', 'sticker', 'System of a Down', 'Edição especial', '/colecao/system-of-a-down/adesivos/edicao-especial-03.webp', NULL, 46),
  ('Rostos', 'sticker', 'System of a Down', 'Edição especial', '/colecao/system-of-a-down/adesivos/edicao-especial-04.webp', NULL, 47),
  ('Microfone', 'sticker', 'System of a Down', 'Edição especial', '/colecao/system-of-a-down/adesivos/edicao-especial-05.webp', NULL, 48),
  ('Edição especial', 'sticker', 'System of a Down', 'Edição especial', '/colecao/system-of-a-down/adesivos/edicao-especial-06.webp', NULL, 49),
  ('Breach', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-01.webp', NULL, 50),
  ('Vocal', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-02.webp', NULL, 51),
  ('Bateria', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-03.webp', NULL, 52),
  ('Ao vivo', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-04.webp', NULL, 53),
  ('Símbolo', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-05.webp', NULL, 54),
  ('Same People New Walls', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-06.webp', NULL, 55),
  ('One Way', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-07.webp', NULL, 56),
  ('Setlist', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-08.webp', NULL, 57),
  ('Robô', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-09.webp', NULL, 58),
  ('Cidade', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-10.webp', NULL, 59),
  ('Selo Breach', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-11.webp', NULL, 60),
  ('Bandeira', 'sticker', 'Twenty One Pilots', 'Breach', '/colecao/twenty-one-pilots/adesivos/breach-12.webp', NULL, 61),
  ('Inauguração Pop', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-01.webp', NULL, 62),
  ('Microfone', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-02.webp', NULL, 63),
  ('Fone', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-03.webp', NULL, 64),
  ('Estrela', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-04.webp', NULL, 65),
  ('DRAP Pop', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-05.webp', NULL, 66),
  ('Vinil', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-06.webp', NULL, 67),
  ('Microfone holográfico', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-07.webp', NULL, 68),
  ('Estrela holográfica', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-08.webp', NULL, 69),
  ('Coração', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-09.webp', NULL, 70),
  ('Fone holográfico', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-10.webp', NULL, 71),
  ('DRAP Pop', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-11.webp', NULL, 72),
  ('Globo espelhado', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-12.webp', NULL, 73),
  ('Inauguração Rock', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-01.webp', NULL, 74),
  ('Mão do rock', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-02.webp', NULL, 75),
  ('Guitarra alada', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-03.webp', NULL, 76),
  ('Amplificador', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-04.webp', NULL, 77),
  ('Caveira coroada', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-05.webp', NULL, 78),
  ('Vinil', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-06.webp', NULL, 79),
  ('Guitarra', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-07.webp', NULL, 80),
  ('Mão do rock cromada', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-08.webp', NULL, 81),
  ('Estrela alada', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-09.webp', NULL, 82),
  ('Caixa de som', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-10.webp', NULL, 83),
  ('DRAP Rock', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-11.webp', NULL, 84),
  ('Raio', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-12.webp', NULL, 85),
  ('Inauguração Futurista', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-01.webp', NULL, 86),
  ('Robô', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-02.webp', NULL, 87),
  ('Nave', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-03.webp', NULL, 88),
  ('Bússola estelar', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-04.webp', NULL, 89),
  ('Infinito', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-05.webp', NULL, 90),
  ('Capacete', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-06.webp', NULL, 91),
  ('Brasão', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-01.webp', NULL, 92),
  ('Castelo', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-02.webp', NULL, 93),
  ('Dragão', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-03.webp', NULL, 94),
  ('Pergaminho', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-04.webp', NULL, 95),
  ('Espada', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-05.webp', NULL, 96),
  ('Ampulheta', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-06.webp', NULL, 97),
  ('Guitarra', 'sticker', 'Nexo Social · Inauguração', 'Edição Rock', '/colecao/nexo-social-inauguracao/adesivos/rock-01.webp', NULL, 98),
  ('Mão do rock', 'sticker', 'Nexo Social · Inauguração', 'Edição Rock', '/colecao/nexo-social-inauguracao/adesivos/rock-02.webp', NULL, 99),
  ('Estrela alada', 'sticker', 'Nexo Social · Inauguração', 'Edição Rock', '/colecao/nexo-social-inauguracao/adesivos/rock-03.webp', NULL, 100),
  ('Caixa de som', 'sticker', 'Nexo Social · Inauguração', 'Edição Rock', '/colecao/nexo-social-inauguracao/adesivos/rock-04.webp', NULL, 101),
  ('Nexo Rock', 'sticker', 'Nexo Social · Inauguração', 'Edição Rock', '/colecao/nexo-social-inauguracao/adesivos/rock-05.webp', NULL, 102),
  ('Raio', 'sticker', 'Nexo Social · Inauguração', 'Edição Rock', '/colecao/nexo-social-inauguracao/adesivos/rock-06.webp', NULL, 103),
  ('Microfone', 'sticker', 'Nexo Social · Inauguração', 'Edição Pop', '/colecao/nexo-social-inauguracao/adesivos/pop-01.webp', NULL, 104),
  ('Estrela', 'sticker', 'Nexo Social · Inauguração', 'Edição Pop', '/colecao/nexo-social-inauguracao/adesivos/pop-02.webp', NULL, 105),
  ('Coração', 'sticker', 'Nexo Social · Inauguração', 'Edição Pop', '/colecao/nexo-social-inauguracao/adesivos/pop-03.webp', NULL, 106),
  ('Fone', 'sticker', 'Nexo Social · Inauguração', 'Edição Pop', '/colecao/nexo-social-inauguracao/adesivos/pop-04.webp', NULL, 107),
  ('Nexo Pop', 'sticker', 'Nexo Social · Inauguração', 'Edição Pop', '/colecao/nexo-social-inauguracao/adesivos/pop-05.webp', NULL, 108),
  ('Globo espelhado', 'sticker', 'Nexo Social · Inauguração', 'Edição Pop', '/colecao/nexo-social-inauguracao/adesivos/pop-06.webp', NULL, 109),
  ('Reino ao entardecer', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-07.webp', NULL, 110),
  ('Cavaleiro', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-08.webp', NULL, 111),
  ('Dragão azul', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-09.webp', NULL, 112),
  ('Brasil clássico', 'sticker', 'DRAP · Inauguração', 'Edição Medieval', '/colecao/drap-inauguracao/adesivos/medieval-10.webp', NULL, 113),
  ('Guitarra em chamas', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-13.webp', NULL, 114),
  ('Caveira de fone', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-14.webp', NULL, 115),
  ('Caixa de som em chamas', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-15.webp', NULL, 116),
  ('Mão do rock alada', 'sticker', 'DRAP · Inauguração', 'Edição Rock', '/colecao/drap-inauguracao/adesivos/rock-16.webp', NULL, 117),
  ('Microfone neon', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-13.webp', NULL, 118),
  ('Coração espelhado', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-14.webp', NULL, 119),
  ('Amizade e música', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-15.webp', NULL, 120),
  ('Estrela neon', 'sticker', 'DRAP · Inauguração', 'Edição Pop', '/colecao/drap-inauguracao/adesivos/pop-16.webp', NULL, 121),
  ('Astronauta', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-07.webp', NULL, 122),
  ('Novos horizontes', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-08.webp', NULL, 123),
  ('Samurai', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-09.webp', NULL, 124),
  ('Planeta', 'sticker', 'DRAP · Inauguração', 'Edição Futurista', '/colecao/drap-inauguracao/adesivos/futurista-10.webp', NULL, 125),
  ('Gatinhos · Doodle vertical', 'wallpaper', 'Gatinhos', 'Doodle', '/colecao/gatinhos/fundos/doodle-vertical.webp', '/colecao/gatinhos/fundos/doodle-vertical-mini.webp', 126),
  ('Gatinhos · Doodle clássico', 'wallpaper', 'Gatinhos', 'Doodle', '/colecao/gatinhos/fundos/doodle-classico.webp', '/colecao/gatinhos/fundos/doodle-classico-mini.webp', 127),
  ('Gatinhos · Doodle panorâmico', 'wallpaper', 'Gatinhos', 'Doodle', '/colecao/gatinhos/fundos/doodle-panoramico.webp', '/colecao/gatinhos/fundos/doodle-panoramico-mini.webp', 128),
  ('Novelo', 'button', 'Gatinhos', 'Doodle', '/colecao/gatinhos/bottons/doodle-01.webp', NULL, 129),
  ('Espreguiçando', 'button', 'Gatinhos', 'Doodle', '/colecao/gatinhos/bottons/doodle-02.webp', NULL, 130)
ON CONFLICT (image_path) DO UPDATE SET
  title = EXCLUDED.title,
  kind = EXCLUDED.kind,
  collection = EXCLUDED.collection,
  edition = EXCLUDED.edition,
  thumb_path = EXCLUDED.thumb_path,
  sort_order = EXCLUDED.sort_order;
